### ISSUE TITLE
Why a global option to choose style instead of six different colorschemes?

### ISSUE THREAD

**Issue by metalelf0** [marko-cerovac/material.nvim#1]
Hi, this is not a real issue, more of a question on my side. I see you have a `g:material_style` option to switch between different variations of your colorscheme. Why didn't you release six different colorschemes, e.g. `material`, `material-darker`, `material-lighter` and so on? I know you're not the first one to do so - `ayu` is the first colorscheme that comes to my mind that is configured the same way - but I'm not a big fan of this solution. Here's why:

- there's more cognitive work required to remember how each colorscheme chooses its variations (e.g. `g:material_style`, `g:ayucolor` and so on; with six different colorschemes, it would just be `:colorscheme material_<tab>` and you get all the versions;
- the variations aren't just shade variations - they are completely different colorschemes. They share the same palette, but one of theme is light, one has a blue tone, and so on.

I understand that your solution doesn't pollute the available colorschemes list with many entries - it's one colorscheme instead of six - but I would consider this an acceptable tradeoff.

Please let me know your reasoning behind this, and thanks for the theme, it really looks great.

**Comment by marko-cerovac** [comment]
Thanks for the compliment.
Well, I haven't thought about it that much.
The material theme that I was using also did it like this, as well as the original VS Code material theme, so i thought I'd do it the same way.
The good thing in all od this is that there is no code repetition. So for example the color value of the background isn't defined 6 times(once for every style)
Instead it's a basic if-else statment that says:
If material_styles is equal to 'deep ocean' 
Blue = #somecolor
Red = #somecolor
...
Elseif material_styles is equal to 'darker'
Blue = #some_other_color
Red = #some_other_color

If you want, I can create stand-alone colorschemes or I can remove other colors and send you the code so you can make a repo and publish it.

**Comment by matu3ba** [comment]
@metalelf0 Colorbuddy allows dynamic setting of colors, so its very nice to adjust the colorscheme to you environment light settings.

@marko-cerovac Can you wrap the setup in a function, so that I can put keymaps or commands for that?

**Comment by metalelf0** [comment]
@matu3ba : yeah, I'm not against different color variations. They are all good. I'm just asking about the opportunity of using a custom variable to choose between colorschemes, which I'm not a big fan of. 

@marko-cerovac , yes, I understand it might be better from a dev perspective to have less repetition, but as an user I think it doesn't add any benefit. In the end, it would just be a matter of configuring the pipeline to spit out six colorschemes instead of one, and I could use your colorschemes just like the vast majority of others, without having to set a custom variable.

**Comment by marko-cerovac** [comment]
@matu3ba That seems like an awesome feature so I'll definitely look into adding it. I just have to figure out how, so it will probably take a few days. If you happen to know how to do it, any help, suggestion or pull request is welcome.

@metalelf0 My plan for this colorscheme in the future is to make it as extensible and configurable as posible. For example being able to toggle theme variations, italic comments, bold variables, underlined error messages etc. I think this is pretty cool since it allows for the user to have more control over the theme and set it up in his/her taste. Later today, I will set up another repo. It will be a clone of this one, but with standalone themes instead of a style variable so you can just use colorscheme oceanic to set a standalone theme. If you want, you can clone it and post it as your own theme to have on your profile.

**Comment by metalelf0** [comment]
@marko-cerovac thanks a lot for your proposal, I won't hijack your work and post it on my profile :) Maybe you could consider setting up a branch of this repo instead of creating a new one? This could also make it easier to keep them aligned.

**Comment by matu3ba** [comment]
@marko-cerovac 

[Some more inspiration](https://github.com/glepnir/zephyr-nvim/blob/main/lua/zephyr.lua), so you dont need to write the [rules for every language](https://github.com/marko-cerovac/material.nvim/blob/main/lua/material.lua#L276) and you could even [async load the color groups](https://github.com/glepnir/zephyr-nvim/blob/main/lua/zephyr.lua#L272), lol.

**Comment by marko-cerovac** [comment]
@metalelf0 Here is the new repo: https://github.com/marko-cerovac/material-config-free.nvim you can set now just use colorscheme material-darker to set the darker variant. I've also left the ability to toggle italic comments, italic keywords(while, for, if, else..) and italic function names in the theme and they are off by default.

@matu3ba Until I make this option available (I have some exams coming up in the next couple of days, so I'm really busy), this new repo seams like a good temporary solution, until i can do it the right way. You can map keys to execute something like :colorscheme material-lighter<CR> and switch themes on the fly.
