### ISSUE TITLE
Use "darker" lualine style only

### ISSUE THREAD

**Issue by kevingriffin** [marko-cerovac/material.nvim#100]
With configuration like

```lua
vim.g.material_style = "darker"
vim.cmd('colorscheme some-other-colorscheme')
--- ...
require('lualine').setup {
  options = {
    theme = 'material-nvim',
--- ...
```

I'd hope that the lualine theme would take on "darker", but it doesn't seem to. If I activate material, the lualine theme applies, but then other things like telescope also get themed, making it hard to go back to a theme that doesn't explicitly theme it.

**Comment by marko-cerovac** [comment]
You need to call the setup function for material.nvim.
Just place ```require('material').setup()``` somewhere before the lualine setup function

**Comment by kevingriffin** [comment]
Thank you!
