### ISSUE TITLE
doesn't support mac's terminal.app

### ISSUE THREAD

**Issue by chenjie199234** [marko-cerovac/material.nvim#102]
![莉莉丝飞书20220704-103340](https://user-images.githubusercontent.com/29348971/177071583-2f63c634-e256-4ebd-8426-4b36c6623231.jpg)

**Comment by marko-cerovac** [comment]
Can you explain the issue in a bit more detail?

**Comment by chenjie199234** [comment]
@marko-cerovac
update the image when use Neovim with this color scheme
can this be fixed
the terminal is mac's original terminal

**Comment by marko-cerovac** [comment]
Do you use treesitter?

**Comment by chenjie199234** [comment]
@marko-cerovac
no.this is because mac's terminal only support 256-color

**Comment by marko-cerovac** [comment]
@chenjie199234 then this issue is beyond the scope of this plugin. The only fix is to change the terminal emulator. I recommend alacritty.
