### ISSUE TITLE
Syntax error in material example config

### ISSUE THREAD

**Issue by listout** [marko-cerovac/material.nvim#106]
There is a syntax error on the example configuration (https://github.com/marko-cerovac/material.nvim#%EF%B8%8F-configuration). 

In the config under **This is an example of the function with the default values**, there is a missing comma (`,`) after `custom_highlights = {}`.  Can you please fix it :)

Relevant error message:
```
Error detected while processing /home/listout/.config/nvim/lua/core/colorscheme.lua:
E5112: Error while creating lua chunk: /home/listout/.config/nvim/lua/core/colorscheme.lua:52: '}' expected (to cl
ose '{' at line 7) near 'plugins'
Press ENTER or type command to continue
```

**Comment by marko-cerovac** [comment]
Fixed, thanks for noticing
