### ISSUE TITLE
Diff is terrible

### ISSUE THREAD

**Issue by sbeyer** [marko-cerovac/material.nvim#107]
This is the best colorscheme I have found so far, however, it has one huge weakness: diffs are terrible hard to read with this theme. To be clear, I am not talking about files with the diff filetype, I am talking about diffs using `diffthis` in more than one buffer or by invoking `nvim -d file1 file2`.

Here is an example of what a diff looks like with the material colorscheme:
![diff with material colorscheme](https://user-images.githubusercontent.com/143889/185722785-122488ed-6071-42e8-85d0-6f3ba74d0e0a.png)

This example is still okay-ish, but together with syntax highlighting the added and modified lines are really hard to spot. In other words, whenever it comes to diffs, I change my colorscheme to something else.

Here's an example of a colorscheme that does it much better:
![diff with default_theme colorscheme of AstroNvim](https://user-images.githubusercontent.com/143889/185722854-d7ec6810-d1fb-41d7-8369-be714c562466.png)

And even vim's default colorscheme is a better choice, although ugly:
![diff with default colorscheme](https://user-images.githubusercontent.com/143889/185722887-62950d31-61f0-4cba-8a9f-e256ef9a637e.png)

Do you agree that this is a use case that needs improvement?

**Comment by marko-cerovac** [comment]
Of course. I didn't open diffs that much, so I guess I just never got around to perfecting it. I'll get it done in the next two days.

**Comment by sbeyer** [comment]
Awesome, thanks! No need to hurry, though :)

**Comment by marko-cerovac** [comment]
Okay, it should be much better now. Let me know if something is still wrong ;)

**Comment by sbeyer** [comment]
It is much better now :-) Thank you!
