### ISSUE TITLE
loading and unloading the theme doesn't work correctly

### ISSUE THREAD

**Issue by folke** [marko-cerovac/material.nvim#11]
I've found two issues that might make the colorscheme work incorrectly depending on what highlight groups the user was using before.

1. it appears ColorBuddy doesn't do a `hi clear`, before setting the highlight groups
2. `material.vim` only `requires` the material lua file, but since requires are cached, the theme will only load the first time. Try switching to a default theme and then back to material. won't work. To fix this, you should probably wrap the lua file in a function and call that function from the vim colors file.

**Comment by marko-cerovac** [comment]
I've added the highlight clear and syntax reset. As far as the require goes, I've tried a couple ways to fix it last night, but couldn't get it to work. Can you please do a pull request if you know how to get it working. In the meantime, I'll keep trying.

**Comment by folke** [comment]
Have you tried adding the below to `material.vim` right before your do the require?

```vim
lua package.loaded['tokyonight'] = nil
```

If not, I'll have a look to see how it can be fixed :)

**Comment by marko-cerovac** [comment]
Wow, that did not occur to me. Thank you so much. The reload works now.
Btw, I saw your post on reddit about your Tokyonight theme. Nice job, Tokyonight and Material are my favorite two themes. I'm glad I can have them both in my config now with LSP and Treesitter support.

**Comment by folke** [comment]
Super! @marko-cerovac ha, same here. Both Material and TokyoNight are the best themes for sure :)
