### ISSUE TITLE
Inconsistent darkening of sign, line number, and fold columns with non_current_windows

### ISSUE THREAD

**Issue by okuuva** [marko-cerovac/material.nvim#112]
With `contrast = { non_current_windows = true }` the fold column of the inactive windows gets darkened while sign column and line numbers do not. While my personal preference would be that all three would get dark background when not active I guess the fold column is the faulty one here.

Example:
![image](https://user-images.githubusercontent.com/2804020/192550900-3261f327-29f5-4b85-abea-b1a885a84780.png)

(Don't mind the `derp` in the config, I put it there just to make signs column stand out).

**Comment by marko-cerovac** [comment]
I'm currently working on a rewrite of the entire plugin. I'll try to solve it in the new version. It will probably require removing the contrast option for line numbers and the sign column. The new version should be ready in about a week.
For now, you can try to solve it in you setup function like this:
```lua
local material = require "material"
local colors    = require "material.colors"

material.setup {
    -- ... your config ...
    custom_highlights = {
        LineNr = { bg = colors.bg_nc },
        SignColumn = { bg = colors.bg_nc },
        FoldColumn = { bg = colors.bg_nc },
}
```

**Comment by okuuva** [comment]
`FoldColumn = { bg = colors.bg_nc },` was enough, thank you! Should I still keep this open? Technically the bug is still there even though there's an easy workaround for it.

**Comment by okuuva** [comment]
Tried it now with just packer and material installed, still the same result. Here's the minimal config I used:

<details>
<summary>Minimal config</summary>

```lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
  local path_sep = on_windows and "\\" or "/"
  local result = table.concat({ ... }, path_sep)
  return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local install_path = join_paths(package_root, "packer", "start", "packer.nvim")
local compile_path = join_paths(install_path, "plugin", "packer_compiled.lua")

local function load_plugins()
  require("packer").startup({
    {
      "wbthomason/packer.nvim",
      "marko-cerovac/material.nvim",
    },
    config = {
      package_root = package_root,
      compile_path = compile_path,
    },
  })
end

local load_config = function()
  local opts = { noremap = true, silent = true }

  -- Shorten function name
  local keymap = vim.api.nvim_set_keymap

  vim.g.mapleader = " "
  vim.g.maplocalleader = " "

  keymap("n", "<C-h>", ":wincmd h<cr>", opts)
  keymap("n", "<C-j>", ":wincmd j<cr>", opts)
  keymap("n", "<C-k>", ":wincmd k<cr>", opts)
  keymap("n", "<C-l>", ":wincmd l<cr>", opts)

  vim.opt.signcolumn = "yes" -- always show the sign column, otherwise it would shift the text each time
  vim.opt.number = true -- set numbered lines
  -- config of the offending plugin here

  vim.g.material_style = "darker"

  local colors = require("material.colors")
  local material = require("material")
  material.setup({

    contrast = {
      sidebars = false, -- Enable contrast for sidebar-like windows ( for example Nvim-Tree )
      floating_windows = false, -- Enable contrast for floating windows
      line_numbers = false, -- Enable contrast background for line numbers
      sign_column = false, -- Enable contrast background for the sign column
      cursor_line = true, -- Enable darker background for the cursor line
      non_current_windows = true, -- Enable darker background for non-current windows
      popup_menu = false, -- Enable lighter background for the popup menu
    },

    italics = {
      comments = true, -- Enable italic comments
      keywords = false, -- Enable italic keywords
      functions = false, -- Enable italic functions
      strings = false, -- Enable italic strings
      variables = false, -- Enable italic variables
    },

    contrast_filetypes = { -- Specify which filetypes get the contrasted (darker) background
      "terminal", -- Darker terminal background
      "packer", -- Darker packer background
      "qf", -- Darker qf list background
    },

    high_visibility = {
      lighter = false, -- Enable higher contrast text for lighter style
      darker = true, -- Enable higher contrast text for darker style
    },

    disable = {
      colored_cursor = false, -- Disable the colored cursor
      borders = false, -- Disable borders between verticaly split windows
      background = false, -- Prevent the theme from setting the background (NeoVim then uses your teminal background)
      term_colors = false, -- Prevent the theme from setting terminal colors
      eob_lines = false, -- Hide the end-of-buffer lines
    },

    lualine_style = "default", -- Lualine style ( can be 'stealth' or 'default' )

    async_loading = false, -- Load parts of the theme asyncronously for faster startup (turned on by default)

    custom_highlights = {
      LineNr = { bg = colors.bg_nc },
      SignColumn = { bg = colors.bg_nc },
      FoldColumn = { bg = colors.bg_nc },
  --[[     NvimTreeNormal = { bg = colors.bg_nc },
      TroubleText = { bg = colors.bg_nc },
      TroubleCount = { bg = colors.bg_nc },
      TroubleNormal = { bg = colors.bg_nc },
      TroubleSignError = { bg = colors.bg_nc },
      TroubleSignWarning = { bg = colors.bg_nc },
      TroubleSignInformation = { bg = colors.bg_nc },
      TroubleSignHint = { bg = colors.bg_nc },
      TroubleIndent = { bg = colors.bg_nc },
      TroubleLocation = { bg = colors.bg_nc }, ]]
    }, -- Overwrite highlights with your own
  })
  local colorscheme = "material"

  local status_ok, _ = pcall(vim.cmd, "colorscheme " .. colorscheme)
  if not status_ok then
    vim.notify("colorscheme " .. colorscheme .. " not found!")
    return
  end
  vim.notify("got here")
end

if vim.fn.isdirectory(install_path) == 0 then
  vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
  load_plugins()
  require("packer").sync()
  local packer_group = vim.api.nvim_create_augroup("Packer", { clear = true })
  vim.api.nvim_create_autocmd(
    "User",
    { pattern = "PackerComplete", callback = load_config, group = packer_group, once = true }
  )
else
  load_plugins()
  require("packer").sync()
  load_config()
end
```
</details>

**Comment by marko-cerovac** [comment]
It's not an issue with the config. Because the theme allows you to set contrast for sign column and number column, their background needs to be higlighted. Neovim wasn't built for this, so it messes up for non-current-windows.
Another thing you could try is:
```lua
custom_highlights = {
        LineNr = { bg = colors.none },
        SignColumn = { bg = colors.none },
        FoldColumn = { bg = colors.none },
    }
```

**Comment by okuuva** [comment]
Ah, that makes sense. Setting the `bg = colors.none` mostly works, now only the lines with diagnostics and the cursor line before changing focused window (line 45) light up:

![image](https://user-images.githubusercontent.com/2804020/193446915-3964ccb7-1067-4107-9048-0b5236797cd4.png)

I guess there's no way around that without changing the internals of material or nvim itself?

**Comment by okuuva** [comment]
> I guess there's no way around that without changing the internals of material or nvim itself?

To answer my own question: there is, it's just a matter of finding the right highlight groups :)
This got rid of number highlights:
```lua
    GitSignsAddNr = { bg = colors.none },
    GitSignsChangeNr = { bg = colors.none },
    GitSignsDeleteNr = { bg = colors.none },
```

Still have highlights in the sign column, will paste the whole config here for the sake of completion once I get that working. Shame that it requires setting these for all the plugins manually but such is life.

**Comment by okuuva** [comment]
Well, got it kinda working. Setting `bg = colors.none` has the unfortunate side effect of setting the sign color to grey, makes it "kinda" hard to separate changed lines from added lines:

![image](https://user-images.githubusercontent.com/2804020/193448914-d90c6002-41e8-4bb7-bbc9-3234e286bd27.png)

**Comment by okuuva** [comment]
Ok, the colors all turned grey because custom highlights override the original completely instead of merging the two (which makes sense now that I think about it). Here's how I fixed the inconsintent column colors:

```lua
custom_highlights = {
    LineNr = { fg = colors.line_numbers, bg = colors.none },
    CursorLineNr = { fg = colors.accent, bg = colors.none },
    SignColumn = { fg = colors.fg, bg = colors.none },
    GitSignsAdd = { fg = colors.green, bg = colors.none },
    GitSignsAddNr = { fg = colors.green, bg = colors.none },
    GitSignsChange = { fg = colors.blue, bg = colors.none },
    GitSignsChangeNr = { fg = colors.blue, bg = colors.none },
    GitSignsDelete = { fg = colors.red, bg = colors.none },
    GitSignsDeleteNr = { fg = colors.red, bg = colors.none },
    DiagnosticSignError = { fg = colors.error, bg = colors.none },
    DiagnosticSignWarn = { fg = colors.yellow, bg = colors.none },
    DiagnosticSignInfo = { fg = colors.paleblue, bg = colors.none },
    DiagnosticSignHint = { fg = colors.purple, bg = colors.none },
  }
```
@marko-cerovac up to you if you want to keep this issue open, this workaround is enough for me.

**Comment by marko-cerovac** [comment]
Okay, I've removed the option for contrasted line_numbers and sign_column. It added unnecessary complexity. I think you will be able to remove most of these custom_highlights now.

**Comment by okuuva** [comment]
Actually all of them :) But now text color became darker, the same hue as comments:
![image](https://user-images.githubusercontent.com/2804020/193507626-8f65d705-2375-4f33-a2fa-c2b4ee1a4345.png)

Looking at the diffs I don't immediately see what would've caused that but I can do a bisect.

**Comment by marko-cerovac** [comment]
I've reverted that change now. It should be good.

**Comment by tdjordan** [comment]
Is there a suggested way to add the contrast for line numbers and sign column back in?

**Comment by tdjordan** [comment]
I figured out that you provided a `custom_highlights` for this scenario.

![Screen Shot 2022-10-14 at 01 02 40](https://user-images.githubusercontent.com/8079/195773922-495428f2-cad4-4f81-8640-e0f80472dc2f.png)

**Comment by marko-cerovac** [comment]
Yeah, these options were adding unnecessary complexity to the theme. They had to be removed.
