### ISSUE TITLE
non_current_windows does not affect sidebar windows

### ISSUE THREAD

**Issue by okuuva** [marko-cerovac/material.nvim#113]
I know this is most likely by design but it still feels a bit inconsistent that `NvimTree`, `Trouble` etc. windows do not get darker background when inactive and `contrast = { non_current_windows = true }` is set. I use that setting to easily differentiate the active window (which I believe is the exact use case for it) and it throws me off when sidebar-like windows are open but have the same background as the open buffer window even though they are not active per se.

![image](https://user-images.githubusercontent.com/2804020/192553110-ca9d9054-4b04-4678-9d8c-e2d7a1ec3f27.png)

**Comment by marko-cerovac** [comment]
Try this:
```lua
local material = require "material"
local colors    = require "material.colors"

material.setup {
    -- ... your config ...
    custom_highlights = {
        NvimTreeNormal = { bg = colors.bg_nc },
        TroubleText = { bg = colors.bg_nc },
        TroubleCount = { bg = colors.bg_nc },
        TroubleNormal = { bg = colors.bg_nc },
        TroubleSignError = { bg = colors.bg_nc },
        TroubleSignWarning = { bg = colors.bg_nc },
        TroubleSignInformation = { bg = colors.bg_nc },
        TroubleSignHint = { bg = colors.bg_nc },
        TroubleIndent = { bg = colors.bg_nc },
        TroubleLocation = { bg = colors.bg_nc },
    }
}
```

**Comment by okuuva** [comment]
Trouble got fixed with that (had to set the `fg` as well to keep the actual colors intact) but nothing seems to affect NvimTree:

![image](https://user-images.githubusercontent.com/2804020/193450285-221242ff-4be1-4121-938f-4b57cbefa485.png)

**Comment by marko-cerovac** [comment]
Does NvimTree get darker background with other colorschemes?
If you set 
```lua
plugins = {
    nvim_tree = false
}
```
then it could be that nvim-tree doesn't play well with the non-current window setting

**Comment by okuuva** [comment]
> This was my mistake. I linked the NvimTreeNormalNC highlight group which is used for this purpose to the NvimTreeNomal group. I've fixed it now. Let me know if it still creates issues.

Works like a charm, takkâ ennuv! The only offenders in NvimTree now are the sign column which gets linked to `NvimTreeNormal` here: https://github.com/kyazdani42/nvim-tree.lua/blob/7282f7de8aedf861fe0162a559fc2b214383c51c/lua/nvim-tree/colors.lua#L85 and root folder that still has explicitly set backgroud here: https://github.com/marko-cerovac/material.nvim/blob/main/lua/material/theme.lua#L395. I fixed these in custom_highlights with `    NvimTreeSignColumn = { link = "SignColumn" },` and `NvimTreeRootFolder = { fg = colors.accent },` respectively but that might be something you want to add to NvimTree plugin settings.

For anyone stumbling to this ticket later: this is how I got Trouble to play ball with `non_current_windows`:
```lua
custom_highlights = {
    TroubleText = { fg = colors.text, bg = colors.none },
    TroubleCount = { fg = colors.purple, bg = colors.none },
    TroubleNormal = { fg = colors.fg, bg = colors.none },
    TroubleSignError = { fg = colors.error, bg = colors.none },
    TroubleSignWarning = { fg = colors.yellow, bg = colors.none },
    TroubleSignInformation = { fg = colors.paleblue, bg = colors.none },
    TroubleSignHint = { fg = colors.purple, bg = colors.none },
    TroubleFoldIcon = { fg = colors.accent, bg = colors.none },
    TroubleIndent = { fg = colors.border, bg = colors.none },
    TroubleLocation = { fg = colors.disabled, bg = colors.none },
  }
```

**Comment by marko-cerovac** [comment]
I've merged the pull request. Let me know if there are any more issues.
