### ISSUE TITLE
either default to disable status message of used color style or add option

### ISSUE THREAD

**Issue by matu3ba** [marko-cerovac/material.nvim#117]
Hello, thanks for the great plugin. Its almost always effortless and just works with great colors.

However, what bothers me on using the disappearing statusline
```lua
vim.o.laststatus = 0 --disappearing statusline
vim.o.cmdheight = 0 -- shortcut vim.o.ch
```
are popping up messages, which require an additonal keypress on each invocation:

![Screenshot_20221009_001550](https://user-images.githubusercontent.com/13089667/194729652-f05f5b8f-81be-4815-b532-be306ee02424.png)

Personally I would not care too much value in seeing the style name that often, but the additional keypress on every new neovim instance opening (to cycle through) is very annoying.

As workaround or nice extra feature for user: Did you implement yet autocompletion suggestions for commands?
Anything usable by the user for this would be great. (Will look into that.)

**Comment by matu3ba** [comment]
Personal workaround, which sounds to me as nice to add to the README:
```lua
add_cmd('Style',
  function(opts)
    require('material.functions').change_style(opts.args)
  end, {
    nargs = 1,
    complete = function(_, _, _)
      return { "darker", "lighter", "palenight", "oceanic", "deep ocean" }
    end,
  }
)
```

**Comment by marko-cerovac** [comment]
I'm currently working on a complete rewrite of the theme. It should be out in about a week. I was even thinking about removing the toggle_style and change_style functions.
For now, you can put this in you config:
```lua
if vim.g.material_style_iterator = nil then
    vim.g.material_style_iterator = 0
end

---toggle between styles
local toggle_style = function()
    local styles = {
        "darker",
        "lighter",
        "palenight",
        "oceanic",
        "deep ocean"
    }
    vim.g.material_style_iterator = (vim.g.material_style_iterator % (#styles)) + 1
    vim.g.material_style = styles[vim.g.material_style_iterator]
    vim.cmd "colorscheme material"
end
vim.keymap.set("n", "YOUR_KEYS", toggle_style, { silent = true })
```

**Comment by matu3ba** [comment]
As of now, still the status message pops up due to a message being printed. What this essentially requires is this patch xor adding an if-condition with configuration variable-check:
```diff
diff --git a/lua/material/functions/init.lua b/lua/material/functions/init.lua
index 563a844..e8cdce2 100644
--- a/lua/material/functions/init.lua
+++ b/lua/material/functions/init.lua
@@ -19,7 +19,6 @@ end
 M.change_style = function(style)
     set_lualine()
     vim.g.material_style = style
-    print("Material style: ", style)
     vim.cmd "colorscheme material"
 end

```

**Comment by matu3ba** [comment]
Never mind, it doesnt show the message, if one does not toggle. So the solution is to define a command and write a message to cmdline with selecting the desired color style.

**Comment by marko-cerovac** [comment]
Ill remove the print statement in the next commit
