### ISSUE TITLE
Add more styles options to code components other than italics

### ISSUE THREAD

**Issue by RayZ0rr** [marko-cerovac/material.nvim#118]
First of all, super theme. Especially the deep ocean and darker.

material provides:
```lua
require('material').setup({

    italics = {
        comments = false, -- Enable italic comments
        keywords = false, -- Enable italic keywords
        functions = false, -- Enable italic functions
        strings = false, -- Enable italic strings
        variables = false -- Enable italic variables
    },

```

But could it be expanded to a section such as follows:

```lua

    styles = {              -- Style to be applied to different syntax groups
      comments = "NONE",    -- Value is any valid attr-list value `:help attr-list`
      conditionals = "NONE",
      constants = "NONE",
      functions = "NONE",
      keywords = "NONE",
      numbers = "NONE",
      operators = "NONE",
      strings = "NONE",
      types = "NONE",
      variables = "NONE",
    },

```

List of some themes that support such settings:

1. https://github.com/EdenEast/nightfox.nvim
2. https://github.com/olimorris/onedarkpro.nvim
3. https://github.com/rmehri01/onenord.nvim
4. https://github.com/catppuccin/nvim
5. https://github.com/folke/tokyonight.nvim
6. https://github.com/navarasu/onedark.nvim

**Comment by marko-cerovac** [comment]
I'm currently working on a complete rewrite of the plugin. The new version will have this feature. It will be done in about a week.
