### ISSUE TITLE
The text color in deep ocean is too dark

### ISSUE THREAD

**Issue by huyvohcmc** [marko-cerovac/material.nvim#12]
I can barely see the word I type in searching, it's very hard for the eyes to notice this color:
<img width="1440" alt="Screen Shot 2021-04-24 at 9 11 34 PM" src="https://user-images.githubusercontent.com/17645203/115961716-ce728100-a541-11eb-8ab7-2e74870d4722.png">

**Comment by marko-cerovac** [comment]
I was trying to follow the material theme guidelines from the theme website, but I have also noticed the lack of contrast. It should be fixed now. Let me know if there are still some visibility issues.
