### ISSUE TITLE
Gitsigns plugin status line is to wide

### ISSUE THREAD

**Issue by kobzar** [marko-cerovac/material.nvim#120]
After last update the gitsigns line look is to wide. 
On the others themes look normaly
[gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim)

Material and tokyonight themes differents
![image](https://user-images.githubusercontent.com/1912842/196676143-4327ede6-0b06-4379-9753-e41b03bea6ce.png)

![image](https://user-images.githubusercontent.com/1912842/196676290-a94b51e0-da09-4d2f-861c-2606c90e4b8d.png)

**Comment by marko-cerovac** [comment]
There was a big update to the theme. Have you seen config in the README?

**Comment by kobzar** [comment]
This is wery strange. 
I try add your configuration, full configuration with all plugins e.t.c
But with the same results. All off another themes work correctly - only in material this bug. 
Can i check something else to understand where is the my mistake?

**Comment by marko-cerovac** [comment]
It's not your mistake, it's mine. I'll fix it by the end of the day.

**Comment by kobzar** [comment]
Isnt fixed

**Comment by marko-cerovac** [comment]
@kobzar what do the lines look like when you issue the command: ```highlight GitSignsAdd gui=reverse``` ?

**Comment by marko-cerovac** [comment]
Closing this for now due to inactivity

**Comment by kobzar** [comment]
This command just change the line color
![image](https://user-images.githubusercontent.com/1912842/198822974-607ab2f9-71af-4415-8087-15cc9ba1b4ad.png)
