### ISSUE TITLE
lighter theme color is hard to recognize with high_visibility on

### ISSUE THREAD

**Issue by tkkcc** [marko-cerovac/material.nvim#128]
Treesitter hightlight is disabled.

On urxvt white background:
![2022-10-20_11-18](https://user-images.githubusercontent.com/17373509/196848682-b4b231a7-b7c0-4b8a-9118-9a3d636b07d2.png)
On kitty default setting:
![image](https://user-images.githubusercontent.com/17373509/196848881-055f09ef-8c1d-43a4-a7bf-94a32ac74702.png)

**Comment by marko-cerovac** [comment]
This could be due to a recent update to treesitter. It uses new highlight groups and I've updated this plugin according to those changes. Is your treesitter updated?

**Comment by tkkcc** [comment]
I use this plugin for several months and `lighter` style is fine. After upgrade nvim to 0.8, it's still ok. Today I upgrade all plugins, then the colors are hard to recognize. 

The `darker` style is fine, so it a `ligher` style issue.
![image](https://user-images.githubusercontent.com/17373509/196938923-0a97ad04-d85d-48c1-a6c9-4efbe7fe870b.png)


nvim version : 0.8.0

treesitter version is latest
```txt
* commit 470b872 (HEAD -> master, origin/master, origin/HEAD)
| Author: José Luis Lafuente <jl@lafuente.me>
| Date:   Thu Oct 20 01:33:31 2022 +0200
```

treesitter config
```lua
  use {
    'nvim-treesitter/nvim-treesitter',
    run = ':TSUpdate',
    config = function()
      require'nvim-treesitter.configs'.setup {
        ensure_installed = "all",
        highlight = {enable = false},
        indent = {enable = false},
      }
    end,
  }
```

**Comment by marko-cerovac** [comment]
It looks like treesitter highlighting is disabled in your config:
```lua
      require'nvim-treesitter.configs'.setup {
        ensure_installed = "all",
        highlight = {enable = false}, -- This should be set to true
        indent = {enable = false},
      }
```

**Comment by tkkcc** [comment]
I always disable treesitter highlight because it can cause huge lagging. So this plugin is not desgined for treesitter highlight off?

**Comment by tkkcc** [comment]
All right. Thanks.
