### ISSUE TITLE
Can't run the plugin, vim.g is nil

### ISSUE THREAD

**Issue by ravingraven** [marko-cerovac/material.nvim#13]
I get the following error when starting neovim with the material colorscheme:

`Error detected while processing /home/myhome/.vim/plugged/material.nvim/colors/material.vim:
line    3:
E5105: Error while calling lua chunk: /home/myhome/.vim/plugged/material.nvim/lua/material.lua:36: attempt to index local 'v' (a nil value)`

No idea why, I'm not that well versed in lua.

**Comment by ravingraven** [comment]
Never mind, just realized that I was on an older version.

**Comment by marko-cerovac** [comment]
Yeah sorry for the inconvenience, but the theme just got a major overhaul.

**Comment by zlesnr** [comment]
I'm seeing something similar.  What's the solution?

`E5105: Error while calling lua chunk: ...eslie/.vim/plugged/material.nvim/lua/material/colors.lua:29: attempt to index field 'g' (a nil value)`

This is using `d546bf4abbcb9ee910eace03b8d4d4d016fe1a1a`.

**Comment by marko-cerovac** [comment]
How does your config look. Can you please paste your theme config in the comments just so I can have more information on the issue
