### ISSUE TITLE
After last breaking changes ruby symbols don't highlight

### ISSUE THREAD

**Issue by nick4tech** [marko-cerovac/material.nvim#133]
After updating to the last version, the highlight for symbols in ruby is no longer enabled. They show as plain variables:

![image](https://user-images.githubusercontent.com/6836442/197740722-f950b452-0080-4829-af3f-893860c00fe0.png)

**Comment by marko-cerovac** [comment]
Should be fixed now, let me know if the issue still persists

**Comment by nick4tech** [comment]
Awesome, thanks!
