### ISSUE TITLE
Various colors broken after recent changes

### ISSUE THREAD

**Issue by sheharyarn** [marko-cerovac/material.nvim#137]
Hi, thank you for all your work on `Material.nvim`.

## Overview

I just ran `:PackerSync` after many weeks to find that a number of colors/highlights are broken or changed now. (The last commit that works for me without issues is de33236e23cab880a1ab3d1cfdc828d3eedbddf8:

```lua
use {
  'marko-cerovac/material.nvim',
  commit = 'de33236e23cab880a1ab3d1cfdc828d3eedbddf8',
}
```

Of the changes that are either broken or affect the vim experience most are:

- Gitsign for file additions have the bg/fg colors reversed
- Border/indent line colors are much brighter (should be the same as comments or lighter)

## Screenshots

Here are some screenshots that demonstrate these issues (ignore the black bar on top, that's because of mac's notch).

On the left side is Neovim with `material.nvim` pinned to the commit mentioned above. On the right side is Neovim with the latest `material.nvim`:

#### Bright Borders in Telescope

<img width="1728" alt="Screen Shot 2022-10-26 at 3 18 41 PM" src="https://user-images.githubusercontent.com/2355108/198149291-9853a07a-3283-4b9b-98bb-03cefa96304f.png">

#### Brighter Indentlines and gitsign colors reversed

<img width="1728" alt="Screen Shot 2022-10-26 at 3 04 14 PM" src="https://user-images.githubusercontent.com/2355108/198148036-73231e18-cc6f-4927-973d-8d8869d17d32.png">

**Comment by marko-cerovac** [comment]
There was a huge update to the theme about a week ago. The setup function has changed also. Take a look at the README. The new options will be there.

**Comment by sheharyarn** [comment]
Thank you for letting me know! I'll go through the README over the weekend to try and update it.

----

Might I also suggest using tagged releases following [Semver](https://semver.org/)? You could encourage using versions in plugin managers in the README like so:

```lua
use { 'marko-cerovac/material.nvim', tag = 'v2.3.*' }
```

This way users can reliably update dependencies automatically. And whenever there's a breaking change, the update process will be intentional by the user since they'll have to explicitly bump the major version. In case of issues, they'll know the exact package responsible and can then look at available documentation such as CHANGELOGs or READMEs to fix those.

Again, thank you for all your work on this plugin!

**Comment by marko-cerovac** [comment]
This change was necessary. It was more of a complete refactor from the ground up. And this new version is built with extensibility in mind. There shouldn't be many breaking changes in the future.
