### ISSUE TITLE
TODO highlighting no longer working

### ISSUE THREAD

**Issue by coltonmorris** [marko-cerovac/material.nvim#139]
First of all, thanks for the great theme! 

There used to be special highlighting for the specific string `TODO`. After updating my setup, it no longer does this. I'm not 100% on whether this plugin was the one giving that functionality, and if so, sorry in advance.

**Comment by coltonmorris** [comment]
after some investigating, I noticed my nvim version was not up to v0.8

https://github.com/marko-cerovac/material.nvim/blob/1ae01db24bc4b7e4434e5edde01cfd416dc805a2/lua/material/highlights/init.lua#L83

after updating, still no success. I'm thinking I probably need to investigate my treesitter setup

**Comment by coltonmorris** [comment]
It works when I disable the `highlight` treesitter module:
`TSBufDisable highlight`

is this expected?

**Comment by marko-cerovac** [comment]
I'll look into it tonight. It could be a missing treesitter highlight group

**Comment by marko-cerovac** [comment]
I've looked into it and tried all possible combinations. This issue first occurred when treesitter started using new highlight groups. For some reason, it recognizes the TODO keyword when it's not commented out, but when it's a part of a comment, it doesn't highlight it. I believe that this is an upstream issue with treesitter.nvim

**Comment by joellidin** [comment]
@marko-cerovac if you set the `@text.note` group it highlights the TODO in comments, I believe.

**Comment by marko-cerovac** [comment]
@joellidin I've tried it, and didn't see any results

**Comment by marko-cerovac** [comment]
It should be fixed now. The only issue is that treesitter still doesn't recognise the word TODO. So you need to use ```TODO:``` instead of ```TODO```

**Comment by kuntau** [comment]
Hi. I can see my `TODO:` in comment have bold style but no highlight color. Is this intentional? using `darker` style
