### ISSUE TITLE
The background is dark if I use different split or popup 

### ISSUE THREAD

**Issue by codeDude64** [marko-cerovac/material.nvim#140]
I usually use the background transparent in my neovim and my terminal emulator, with just one buffer, works fine, when I open `telescope` or `nvim_tree` all the background changes to be dark.

![Peek 2022-10-28 17-52](https://user-images.githubusercontent.com/35637860/198747729-81d2c5d0-117d-419e-bcdf-5201b6522257.gif)

I've changed my configuration to the new version, just like the documentation suggested. I don't know if this is an error with my setup or an issue with the color scheme.

In any case I attaching my set up here.

```lua
local material = require 'material'

vim.g.material_style = 'palenight'

material.setup({
  contrast = {
    terminal = false, -- Enable contrast for the built-in terminal
    sidebars = false, -- Enable contrast for sidebar-like windows ( for example Nvim-Tree )
    floating_windows = false, -- Enable contrast for floating windows
    cursor_line = false, -- Enable darker background for the cursor line
    non_current_windows = false, -- Enable darker background for non-current windows
    filetypes = {}, -- Specify which filetypes get the contrasted (darker) background
  },
  styles = { -- Give comments style such as bold, italic, underline etc.
    comments = { italic = true },
    strings = { bold = true },
    keywords = { underline = true },
    functions = { bold = true, italic = true },
    variables = {},
    operators = {},
    types = {},
  },
  plugins = { -- Uncomment the plugins that you use to highlight them
    -- Available plugins:
    "dap",
    -- "dashboard",
    "gitsigns",
    -- "hop",
    -- "indent-blankline",
    -- "lspsaga",
    -- "mini",
    "neogit",
    "nvim-cmp",
    -- "nvim-navic",
    "nvim-tree",
    -- "sneak",
    "telescope",
    -- "trouble",
    -- "which-key",
  },
  disable = {
    colored_cursor = false, -- Disable the colored cursor
    borders = false, -- Disable borders between verticaly split windows
    background = true, -- Prevent the theme from setting the background (NeoVim then uses your terminal background)
    term_colors = false, -- Prevent the theme from setting terminal colors
    eob_lines = false -- Hide the end-of-buffer lines
  },
  high_visibility = {
    lighter = false, -- Enable higher contrast text for lighter style
    darker = false -- Enable higher contrast text for darker style
  },
  lualine_style = "default", -- Lualine style ( can be 'stealth' or 'default' )
  async_loading = true, -- Load parts of the theme asyncronously for faster startup (turned on by default)
  custom_colors = nil, -- If you want to everride the default colors, set this to a function
  custom_highlights = {}, -- Overwrite highlights with your own
})

vim.cmd 'colorscheme material'

```

**Comment by Rodrigodd** [comment]
Also stumble on this same issue after updating. It seems like `hi NormalNC` is not being set to `NONE` when `disable.background = true`. Setting `custom_highlights.NormalNC = { bg = 'NONE' }` fixed that for me.

**Comment by codeDude64** [comment]
> Also stumble on this same issue after updating. It seems like `hi NormalNC` is not being set to `NONE` when `disable.background = true`. Setting `custom_highlights.NormalNC = { bg = 'NONE' }` fixed that for me.

Well in my case it isn't fixed at all, The background now is ok on the primary buffer and the split one, but the telescope pop-up and the nvim-tree buffer still get a solid background.

I think that I can use this solution at the moment, but I'll keep this issue open.

![Peek 2022-10-31 22-55](https://user-images.githubusercontent.com/35637860/199162073-04d7ed6e-58f6-4979-8cac-a2ddc20bc2c2.gif)

**Comment by achimnol** [comment]
Same problem here!

**Comment by marko-cerovac** [comment]
I've added a fix for this option.

Please let me know if it works.

**Comment by codeDude64** [comment]
> I've added a fix for this option.
> 
> Please let me know if it works.

It works for me :+1:

**Comment by achimnol** [comment]
Yes, I just updated the plugin and it works as expected!
