### ISSUE TITLE
New styles block for functions changes display behavior of curly brackets.

### ISSUE THREAD

**Issue by tdjordan** [marko-cerovac/material.nvim#142]
Love this theme.

I just upgraded to the latest version ( post-refactor ).
One unexpected change is that the `style.functions` setting for italics is effecting all curly bracket instances.

Here is a screenshot showing the effect of the of setting function italic to true or false.

<img width="1605" alt="Screen Shot 2022-11-01 at 15 50 55" src="https://user-images.githubusercontent.com/8079/199342257-e88995de-15c2-4ef2-be93-14ee6588f96a.png">

And here is a screenshot showing curly brackets before the refactor.

![Screen Shot 2022-10-14 at 01 12 32](https://user-images.githubusercontent.com/8079/199342446-c5cd9c2e-e7f7-4c93-af45-dbefeb6d5d6f.png)

**Comment by tdjordan** [comment]
Looking at this a little more closely, it appears like Treesitter is correctly identifying the bracket as a `table_constructor`.

<img width="2084" alt="Screen Shot 2022-11-01 at 16 16 23" src="https://user-images.githubusercontent.com/8079/199343612-31676b42-2303-480f-854a-c1071de1a8ba.png">

And then the theme is linking `@constructor` to functions here : https://github.com/marko-cerovac/material.nvim/blame/main/lua/material/highlights/init.lua#L95

![Screen Shot 2022-11-01 at 16 17 11](https://user-images.githubusercontent.com/8079/199343952-a6f0749c-cbd1-4cf4-b439-50bc541e9da4.png)

**Comment by marko-cerovac** [comment]
I've fixed the link. The unfortunate thing is that table brackets in lua are going to be blue by default instead of cyan because changing the @constructor highlight group would mess up constructors in other languages.
