### ISSUE TITLE
Add support for vim help.

### ISSUE THREAD

**Issue by GnikDroy** [marko-cerovac/material.nvim#143]
Highlighting has poor contrast on vim help windows when using material deep ocean.

![image](https://user-images.githubusercontent.com/30725674/199719251-7afd500b-89a9-4ac1-85c4-1b70b97526a6.png)

An example using the `onedark` colorscheme.

![WindowsTerminal_9RUGhlvlvb](https://user-images.githubusercontent.com/30725674/199719295-3d1c966e-1430-44eb-9f3b-9ccbf05cf09e.png)

**Comment by bryant-the-coder** [comment]
`:TSInstall help`

**Comment by GnikDroy** [comment]
@bryant-the-coder the two screenshots above are from the same neovim instance. 

I only switched colorschemes with `:colo onedark`. Treesitter installation is fine. Anyway, :TSInstallInfo also marks help as installed.

**Comment by marko-cerovac** [comment]
There were two highlight groups that were missing. I've added them now. It should be much better.

**Comment by marko-cerovac** [comment]
Highlighting for parameters like ```{callback}``` and ```{function}``` can't be added.

**Comment by GnikDroy** [comment]
It does work indeed. The contrast is very low for examples in help. Maybe we could use a different color for that? Other than that, it's fine.

Feel free to close this.

**Comment by marko-cerovac** [comment]
Great, I'll improve this further in the future.
