### ISSUE TITLE
contrast.filetypes not working for toggleterm

### ISSUE THREAD

**Issue by anurag3301** [marko-cerovac/material.nvim#145]
Hey I use this [toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim) plugin for my terminal emulator in neovim.
I want the toggleterm window to be darker in contrast, so I added the following configuration
```lua
    contrast = {
        terminal = false,
        sidebars = true,
        floating_windows = true,
        cursor_line = false,
        non_current_windows = false,
        filetypes = {
            'terminal',
            'packer',
            'qf',
            'toggleterm'
        },
    },
```
I have added the `toggleterm` as filetype but its not working.
![image](https://user-images.githubusercontent.com/52702259/200122614-c0d19434-9f0f-4ea6-b2e7-5249df6cc7de.png)
If there is any mistake in my config, please let me know how should I fix this.

**Comment by anurag3301** [comment]
### This is my config
```lua
-- Material Theme config
vim.g.material_style = 'deep ocean'

require('material').setup({

    contrast = {
        terminal = false,
        sidebars = true,
        floating_windows = true,
        cursor_line = false,
        non_current_windows = false,
        filetypes = {
            'terminal',
            'packer',
            'qf',
            'toggleterm'
        },
    },

    styles = {
        comments = { italic = true },
        strings = {},
        keywords = {},
        functions = { italic = true },
        variables = {},
        operators = {},
        types = { bold = true },
    },

    plugins = {
        -- "dap",
        "dashboard",
        "gitsigns",
        "hop",
        -- "indent-blankline",
        -- "lspsaga",
        -- "mini",
        -- "neogit",
        "nvim-cmp",
        -- "nvim-navic",
        "nvim-tree",
        -- "sneak",
        "telescope",
        -- "trouble",
        -- "which-key",
    },

    disable = {
        colored_cursor = false,
        borders = false,
        background = false,
        term_colors = false,
        eob_lines = false
    },

    high_visibility = {
        lighter = false,
        darker = false
    },

    lualine_style = "default",

    async_loading = true,

    custom_colors = nil,

    custom_highlights = {},
})

vim.cmd 'colorscheme material'

vim.cmd("highlight WinSeparator guifg=#c0bfbc")
```

**Comment by marko-cerovac** [comment]
What is the output when you run the command ```:set filetype``` in toggleterm?

**Comment by anurag3301** [comment]
Its `filetype=toggleterm`

**Comment by anurag3301** [comment]
The bufferline.nvim plugin shows the same thing
![image](https://user-images.githubusercontent.com/52702259/200127807-75736c65-a178-476b-9f1f-da059461ca30.png)

**Comment by marko-cerovac** [comment]
Toggleterm uses it's own highlight system. You need to set the background to ```NormalContrast``` in your toggleterm settings if you want it to have a darker background.
```lua
require("toggleterm").setup({
    highlights = {
        Normal = {
            guibg = "NormalContrast"
        }
    }
})
```

**Comment by anurag3301** [comment]
Hey I tried adding this in my toggleterm config but it didn't work
```lua
  highlights = {
    Normal = {
       guibg = "#090b10"
    }
  }
```
Should I create an issue in toggleterm and mention this issue over there?

**Comment by anurag3301** [comment]
Okay my bad, just revised my config and this line was causing the problem
```
   shading_factor = 1,
```
I removed it and its working
![image](https://user-images.githubusercontent.com/52702259/200323004-6cad44c7-b777-4d40-af95-2b6d4e380e6d.png)
Thanks for you help

**Comment by marko-cerovac** [comment]
guibg doesn't take a color as an argument, it takes a different highlight group to link to. Instead of ```#090b10```, just put ```NormalContrast```.

**Comment by anurag3301** [comment]
Oh okay, I changed it to `NormalContrast`, Thank you :)
