### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Chaitanyabsprip** [marko-cerovac/material.nvim#15]
add option for transparent bg

**Comment by marko-cerovac** [comment]
Well, just giving the background some transparency would be really difficult, but I can add an option to disable the background to be set. This means, that NeoVim will have the same background as your terminal. So if you use a transparent terminal, the background will be transparent. Is this similar to what you had in mind?

**Comment by Chaitanyabsprip** [comment]
Yes, I have actually implemented this is a horizon color scheme, you can set the background to none and that'll allow for the terminal bg to be visible, if someone is using picom to add transparency and blur to the terminal then they'll have a transparent background for nvim too with your colorscheme applied.

**Comment by marko-cerovac** [comment]
That's exactly what I meant in the comment above. I've added the option. It's called material_disable_background and
it will disable the Normal background color, as well as the Signcolumn and NvimTree bacground

**Comment by georgeiliadis91** [comment]
After trying to figure out how to do it, I found this thread. May I suggest, to add it on the docs?
