### ISSUE TITLE
Neogit switch not highlighted

### ISSUE THREAD

**Issue by kuntau** [marko-cerovac/material.nvim#153]
I have `neogit` listed in plugins. 

When you do any action in neogit that have switch <kbd>-</kbd> ex. `-f` normally the switch will be highlighted but I got no visual feedback

running `NVIM v0.9.0-dev-cb9d68fe` on macos

**Comment by marko-cerovac** [comment]
Can you please give some more context? How can I reproduce the issue?

**Comment by kuntau** [comment]
Take a look at this [asciinema recording](https://asciinema.org/a/j3LN9LuwU9YzmOgvktxBBuTH2)

The first colorscheme is `nightfox`. Notice the switch highlighted in `neogit` window.

**Comment by kuntau** [comment]
![549736](https://user-images.githubusercontent.com/327489/210905481-6f7e8f44-4563-4b56-b636-df12e72da257.gif)

**Comment by marko-cerovac** [comment]
Thanks for the PR. I was busy these days and haven't got around to working on the issue yet.
