### ISSUE TITLE
Search and IncSearch bg may change to e.highlight

### ISSUE THREAD

**Issue by gxt-kt** [marko-cerovac/material.nvim#157]
First of all, thank for your materail plugin. It's my favorite color scheme   plugin.
The default "Search" and "IncSearch" bg is `e.selection`. I think it's better to change to `e.highlight`. Thus l can change the search highlight color to yellow or somewhat bright color.
Also if someone want change the default color, add this config 
```
custom_highlights = {
          IncSearch = { fg = "#000000", bg = "#FABD2F", underline = true },
          Search    = { fg = "#000000", bg = "#FADB2F", bold = true },
}
```
Thank you.

**Comment by marko-cerovac** [comment]
I'm working on adding new colors for better search visibility. It will be done in about a week.

**Comment by marko-cerovac** [comment]
Im still looking for better colors for Search and IncSearch. For now, I've made them more visible by making them white.
