### ISSUE TITLE
Feature:  Add neorg support

### ISSUE THREAD

**Issue by trev-dev** [marko-cerovac/material.nvim#159]
I think we may be missing some highlight groups from Neorg.  Things like `:hi @text.emphases` and `:hi @text.strong` are empty.  These are both used by Neorg for italic and bold markup text respectively.

Not sure how many other Neorg users there are who use this theme and can confirm this.  I may try to add something myself later on and see if it works.

**Comment by marko-cerovac** [comment]
I'm working on it currently.

**Comment by marko-cerovac** [comment]
I've added bold and italic text as well as some basic support for neorg.
More improvements are comming.

**Comment by trev-dev** [comment]
@marko-cerovac Really nice, thank you!
