### ISSUE TITLE
Highlight color for colorcolumn option

### ISSUE THREAD

**Issue by LuisxSullivaN** [marko-cerovac/material.nvim#16]
I noticed when I set the colorcolumn option it displays that column with the same color as the background:
![image](https://user-images.githubusercontent.com/29529436/116340145-4a6c0380-a7a4-11eb-826a-a370f1016fb9.png)

Shouldn't it be showing up with a different color?

**Comment by marko-cerovac** [comment]
Yeah, I defined it's foreground instead of the background, sorry.
It should all be fixed now, let me know if there's any more issues ;)
