### ISSUE TITLE
printing "Material style" interferes with startup

### ISSUE THREAD

**Issue by miguelbarao** [marko-cerovac/material.nvim#160]
Best colorscheme except for a little detail :)

Neovim now allows setting `cmdheight=0` so that the status bar is at the bottom of the terminal window. With this configuration, prints to the command line wait for a key press before continuing.

Because of this, the print in `lua/material/functions/init.lua:22` prevents neovim from starting and always wait for a keypress before continuing. This is extremely annoying.

Would you consider removing this print? (or disabling it)

**Comment by marko-cerovac** [comment]
I've removed the print. But I believe that something is not right with your config. That function doesn't get called on startup. It only gets called explicitly. For example when changing styles with a key mapping or the telescope function.

**Comment by miguelbarao** [comment]
Thank you.
Yes, I'm calling the function explicitly. I use the lazy package manager and setup material with
```lua
{
    'marko-cerovac/material.nvim',
    priority = 1000,
    opts = {
       -- options here...
    },
    config = function(_, opts)
      require('material').setup(opts)
      require('material.functions').change_style('darker')
    end,
}
```

**Comment by marko-cerovac** [comment]
@miguelbarao by doing it that way, you colorscheme gets loaded two times. It first gets loaded with the default (oceanic) style, and then, when you call change_style, it gets loaded a second time with the darker style. Instead, you should use:
```lua
config = function(_, opts)
    vim.g.material_style = "darker"
    require("material").setup(opts)
    vim.cmd 'colorscheme material'
end
```

**Comment by miguelbarao** [comment]
Thanks for pointing that out.
