### ISSUE TITLE
Could the different styles not be part of the main telescope plugin ':Telescope colorscheme"? Having yet another menu feels like overkill

### ISSUE THREAD

**Issue by emilBeBri** [marko-cerovac/material.nvim#161]
Hi so I love the colors, but I don't understand why I would need Yet Another telescope menu, which means Yet Another keybinding:

```
vim.g.material_style = "deep ocean"
```

Most other colorschemes, you can select which flavour you want in the telescope picker menu with this command, as you are probably already familiar

```
Telescope colorscheme
```

Could this be implemented, possibly just as an option? Or if there is some higher reason to do it like this, I'd be happy to understand it. I hope you can follow my reasoning that I would rather have the different flavours in the already-present telescope color theme picker.

**Comment by marko-cerovac** [comment]
Sure, I'll implement it in the next few days. The reason for this is:
I was playing around with writing telescope pickers a long time ago and wrote that function. Back then, no other colorscheme had the option to use telescope. I thought it was pretty cool, so I left it there. I guess it's time to refresh it.

**Comment by marko-cerovac** [comment]
Done. The styles can now be set by using the regular ```Telescope colorscheme``` command.

**Comment by emilBeBri** [comment]
Thanks man. Appreciate it 🙏
