### ISSUE TITLE
Inactive windows dim effect seems "reversed" for lighter style

### ISSUE THREAD

**Issue by gautaz** [marko-cerovac/material.nvim#164]
Hello,

One might expect that non current windows are dimmed compared to the current window.
What should be "dimming" is probably entirely subjective in terms of colors.
But AFAIC, this would mean that the current window should be lighter than non current windows.

Currently when enabling `contrast.non_current_windows` in lighter mode, the current window is darker than non current windows (at least on my workstation):

![image](https://github.com/marko-cerovac/material.nvim/assets/11046232/0a2d80b9-918a-457f-93ca-de22f7f1af4e)

This is not what is expected when one reads the documentation which states:

> Enable darker background for non-current windows

Am I the only one experiencing this behavior?
Is this behavior expected?
What is the general opinion on this matter?

**Comment by marko-cerovac** [comment]
No, this is the intended color for non-current windows. You see, the theme has two main colors that it uses for backgrounds. The main color, and the contrasted color (which is darker for dark themes, and lighter for the light theme). The ```non_current_window``` option applies the contrasted color for non-current windows. I will fix the README later today to clear up the confusion. As far as changing the color to a darker one, it would require a lot of changes to the plugin structure. You can also always change the color in your settings like this:
```lua
require('material').setup {
    custom_colors = function(colors)
        colors.backgrounds.non_current_windows = "#YOUR_NEW_COLOR"
    end
}
```

**Comment by gautaz** [comment]
Thank you for your answer :smiley:.
If this is the intended behavior, this is perfectly fine.
The "dimming" behavior can in fact be obtained by tweaking the color settings.
Do you want me to keep the issue opened until the README reflects this intent?

**Comment by marko-cerovac** [comment]
It's changed now
