### ISSUE TITLE
Enable theme selection through :Telescope colorscheme

### ISSUE THREAD

**Issue by ema2159** [marko-cerovac/material.nvim#166]
Hi! Is it possible to implement something similar to [this other request I made](https://github.com/loctvl842/monokai-pro.nvim/issues/41). In summary, It would be nice to have all the variants exposed as individual themes so they could be picked using `:Telescope colorscheme`.

Thanks!

**Comment by marko-cerovac** [comment]
Done. You can now use ```colorscheme material-<style>```.
