### ISSUE TITLE
Telescope too dark

### ISSUE THREAD

**Issue by sbeyer** [marko-cerovac/material.nvim#167]
Since commit e08b1c1 Telescope is way too dark. All the colors are dark gray now and it's hard to see.

My material config to reproduce: https://github.com/sbeyer/neovim-config/blob/main/plugins/colorscheme.lua

**Comment by marko-cerovac** [comment]
This was done to make the theme more similar to the VSCode material theme. But since it doesn't look good in all styles, I've reverted the change. Should be better now.
