### ISSUE TITLE
New material `colors.editor.fg_dark` too dark

### ISSUE THREAD

**Issue by aidan-smith** [marko-cerovac/material.nvim#168]
The color change made in commit e08b1c1 is far too dark in my opinion when contrasted with the oceanic background, to the point that I have pinned the plugin to the previous commit. 

I would assume that others are having similar issues, as going from #7C9EAD -> #4B504F makes quite a big difference visually in terms of readability. I'm sure you had good reason to change the color, but I much prefer the previous color, and ask that it is either reverted, or at least made a bit lighter, such that it contrasts with the background better.

**Comment by marko-cerovac** [comment]
My bad, I've uncommented the wrong line. Should be fixed now.

**Comment by aidan-smith** [comment]
I didn't see the change in your most recent commit 89e9eb31941100388c80476d8edf1099a15b1872 so I've opened a PR. It seems like you may have just forgot to stage this change, as I can see the telescope change you mentioned?

**Comment by marko-cerovac** [comment]
@aidan-smith You're right, looks like I forgot to stage it. Thanks for the fix.
