### ISSUE TITLE
Add vim-treesitter-context support

### ISSUE THREAD

**Issue by pevhall** [marko-cerovac/material.nvim#170]
Request support for [nvim-treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context).

current work around
`highlight TreesitterContext guibg=black
`

**Comment by marko-cerovac** [comment]
Done. the background is darker now

**Comment by pevhall** [comment]
Only the background for the line numbers seems to be changing for me (see pick below). It's definitely an improvement but I think making the whole line stand out would be better.

![material-context](https://github.com/marko-cerovac/material.nvim/assets/23369812/a37bd587-0a9f-4c06-ac4d-174ffb30b3c9)

**Comment by marko-cerovac** [comment]
@pevhall I've fixed the highlighting . It should be working perfectly now. Sorry for the wait and let me know if there is anything else to fix.

**Comment by pevhall** [comment]
Thanks @marko-cerovac it works perfectly now

![Screenshot_20230710_124210](https://github.com/marko-cerovac/material.nvim/assets/23369812/23779a2f-b351-4340-a360-c847df8cabc3)
