### ISSUE TITLE
Tab colours aren't in Material colours

### ISSUE THREAD

**Issue by roubaobaozi** [marko-cerovac/material.nvim#173]
Hi! Switched to this instead of the non-lua material theme, but noticed this:

<img width="323" alt="image" src="https://github.com/marko-cerovac/material.nvim/assets/5126295/4382cb45-631a-4bc6-aff7-c305fea3d1c0">

Tab colours aren't that Material blue. Did I do something wrong, or was it missed?

**Comment by marko-cerovac** [comment]
Are you using the ```darker``` variant?

**Comment by roubaobaozi** [comment]
I am! I'm … starting to get the distinct feeling that it's "meant to be that way" for darker haha.

Will close this. Thanks!
