### ISSUE TITLE
MatchParen not visible with 'deep ocean' theme

### ISSUE THREAD

**Issue by tomaskallup** [marko-cerovac/material.nvim#18]
Hi, thanks for this great colorscheme.
I'm using the `deep ocean` variant and I'm having trouble seeing `MatchParen` (automatically highlighted matching parenthesis when cursor is on a parenthesis). Would it be possible to add an option to make it at least bold? That makes it a bit more distinguishable from others.

**Comment by marko-cerovac** [comment]
Thanks for noticing. I'm trying to get all the little details correct and it's easy to miss something. I've changed it to bold and changed the color to yellow just to make them stand out a bit more.

**Comment by tomaskallup** [comment]
Perfect, thank you!
