### ISSUE TITLE
The colors are different from the colors in vscode

### ISSUE THREAD

**Issue by niba** [marko-cerovac/material.nvim#180]
Material is my favourite theme in vscode and I wanted to match my neovim configuration with vscode. I don't know why but material.nvim displays totally different colors than the offical vscode material plugin.

Quick comparison (Typescript)

VSCode - Material
![image](https://github.com/marko-cerovac/material.nvim/assets/2017454/c71961f6-f459-4632-bc86-334f2db22b66)

Neovim - Material
![image](https://github.com/marko-cerovac/material.nvim/assets/2017454/77c1799e-e2d1-4c43-babe-51bc652ac143)

VSCode - Material Palenight
![image](https://github.com/marko-cerovac/material.nvim/assets/2017454/c4423a13-1e89-4fc4-9dda-63d3d0ea60cf)

Neovim - Material Palenight
![image](https://github.com/marko-cerovac/material.nvim/assets/2017454/e400bba2-6f62-4b3b-a789-713d5197bebb)

I have treesitter etc so I don't know why my colors are so weird

**Comment by marko-cerovac** [comment]
The colors in this theme are based on the original jetbrains theme, but I was planing on matching the VSCode colors sometime in the future. I'll implement it over the next few days.
