### ISSUE TITLE
Can't see text in `neotree` if not run `colorscheme material-darker`

### ISSUE THREAD

**Issue by Anifyuli** [marko-cerovac/material.nvim#185]
Hello, Mister. I get small problem using this colorscheme. That is if I not run `:colorscheme material-darker`, confirmation dialog in `Neotree` not readable. It's quiet complicated if it can readable with executing that command every opening Nvim. I'm using Astro Nvim as Nvim config distribution and it use Lazy.nvim as plugin manager. It's my config

```lua
return {
  "marko-cerovac/material.nvim",
  enable = true,
  lazy = false,
  priority = 1000,
  init = function() -- init function runs before the plugin is loaded
    vim.g.material_style = "darker"
  end,
  opts = {
    contrast = {
      terminal = false, -- Enable contrast for the built-in terminal
      sidebars = false, -- Enable contrast for sidebar-like windows ( for example Nvim-Tree )
      floating_windows = false, -- Enable contrast for floating windows
      cursor_line = false, -- Enable darker background for the cursor line
      non_current_windows = false, -- Enable contrasted background for non-current windows
      filetypes = {}, -- Specify which filetypes get the contrasted (darker) background
    },

    styles = { -- Give comments style such as bold, italic, underline etc.
      comments = { --[[ italic = true ]]
      },
      strings = { --[[ bold = true ]]
      },
      keywords = { --[[ underline = true ]]
      },
      functions = { --[[ bold = true, undercurl = true ]]
      },
      variables = {},
      operators = {},
      types = {},
    },

    plugins = { -- Uncomment the plugins that you use to highlight them
      -- Available plugins:
      -- "dap",
      -- "dashboard",
      -- "eyeliner",
      -- "fidget"
      -- "flash"
      -- "gitsigns",
      -- "harpoon",
      -- "hop",
      -- "illuminate",
      -- "indent-blankline",
      -- "lspsaga",
      -- "mini",
      -- "neogit",
      -- "neotest",
      -- "neorg",
      -- "noice"
      "nvim-cmp",
      -- "nvim-navic",
      -- "nvim-tree",
      "nvim-web-devicons",
      -- "rainbow-delimiters",
      -- "sneak",
      "telescope",
      -- "trouble",
      "which-key",
    },

    disable = {
      colored_cursor = false, -- Disable the colored cursor
      borders = false, -- Disable borders between verticaly split windows
      background = false, -- Prevent the theme from setting the background (NeoVim then uses your terminal background)
      term_colors = false, -- Prevent the theme from setting terminal colors
      eob_lines = false, -- Hide the end-of-buffer lines
    },

    high_visibility = {
      lighter = false, -- Enable higher contrast text for lighter style
      darker = true, -- Enable higher contrast text for darker style
    },

    async_loading = true, -- Load parts of the theme asyncronously for faster startup (turned on by default)

    custom_colors = nil, -- If you want to override the default colors, set this to a function

    custom_highlights = {},
  },
}
```
I enable it and exclude it from lazy loading, and I change priority too it's not changed anymore. I'm write in `init.lua` like this `colorscheme "material"` and I change it to `colorscheme "material-darker"`, but it can't change anymore. You can see in this picts below.

Before execute `:colorscheme material-darker`
![Screenshot from 2023-12-10 20-41-15](https://github.com/marko-cerovac/material.nvim/assets/73734843/9dc46f72-31ce-4c39-bcdf-9ca3bc357368)

After executing `:colorscheme material-darker`
![Screenshot from 2023-12-10 20-41-45](https://github.com/marko-cerovac/material.nvim/assets/73734843/92b62ea6-3d1b-46b5-9a90-139f226e9568)

I wish this small appearance problem can solved. Thanks for your answer, Mister.

**Comment by Anifyuli** [comment]
Thanks, Mister. I glad you fix it

**Comment by marko-cerovac** [comment]
I added support for nvim-tree and the problem should be fixed now.
Just add:
```lua
require 'material'.setup {
    plugins = {
        "neo-tree"
    }
}
```
to you config to enable the support for neo-tree.

**Comment by Anifyuli** [comment]
> I added support for nvim-tree and the problem should be fixed now. Just add:
> 
> ```lua
> require 'material'.setup {
>     plugins = {
>         "neo-tree"
>     }
> }
> ```
> 
> to you config to enable the support for neo-tree.

I'll try it. I wish it can be solved

**Comment by Anifyuli** [comment]
![image](https://github.com/marko-cerovac/material.nvim/assets/73734843/9e4bf175-8772-47e8-b21d-fb2316f73784)
It better and look nice. Thanks, Mister
