### ISSUE TITLE
How can I disabled underline like this?

### ISSUE THREAD

**Issue by a1401358759** [marko-cerovac/material.nvim#186]
![image](https://github.com/marko-cerovac/material.nvim/assets/15830146/2b59b32c-0ac3-4002-a9c4-917acbeb100d)

**Comment by marko-cerovac** [comment]
This is weird. First of all, you don't need set all those values to ```underline = false, undercurl = false```. They are false by default. As far as the strange underline goes I don't think this is comming from the colorscheme. Is only the word under the cursor underlined?

**Comment by a1401358759** [comment]
@marko-cerovac yes,only the word under the cursor underlined

**Comment by a1401358759** [comment]
maybe I've found the reason

![image](https://github.com/marko-cerovac/material.nvim/assets/15830146/e286c01c-f726-4299-9c1c-4fddd7d99d35)

the `vim-illuminate` plugin underline
