### ISSUE TITLE
tree-sitter highlights broken since introduction of Neovim (nightly) default colourscheme

### ISSUE THREAD

**Issue by mrcjkb** [marko-cerovac/material.nvim#188]
Note: I just wanted to open this for reference, and am not asking for a fix, as I am on neovim nightly :smile: 

_______

Hey :wave: 

I've noticed some broken tree-sitter highlighting and git bisected it to https://github.com/neovim/neovim/pull/26334.

Specifically, Neovim used to highlight according to the last match in the highlights.scm file.

### Before the PR:

Notice how `spec` matches `@variable.haskell` last and is highlighted accordingly

![treesitter](https://github.com/neovim/neovim/assets/12857160/3c576d81-e919-424a-8328-70456244293c)

### After the PR:

Now `spec` is highlighted as `@function.haskell`

![image](https://github.com/neovim/neovim/assets/12857160/eeb0a311-ee6f-464a-b55e-63dac45a441f)

I've tested it with another coluorscheme (catppuccin), and cannot reproduce the behaviour:

![catppuccin](https://github.com/marko-cerovac/material.nvim/assets/12857160/64a21992-9623-453b-b17b-70016dfcad90)

So it appears to be specific to this plugin.

**Comment by mrcjkb** [comment]
This is because this plugin doesn't define all tree-sitter highlight groups, falling back to Neovim's defaults (many of which are currently undefined on nightly).

**Comment by marko-cerovac** [comment]
Sorry, I had some exams so I didn't have time to respond to issues earlier

**Comment by mrcjkb** [comment]
> Sorry, I had some exams so I didn't have time to respond to issues earlier

No worries. Hope they went well :smile: 

Thanks for maintaining this awesome colorscheme!
