### ISSUE TITLE
[Question] how to prevent changing highlight for dashboard?

### ISSUE THREAD

**Issue by Young1783** [marko-cerovac/material.nvim#19]
I know this theme set highlight group for Dashborad. But I wonder know how to prevent it?
I try to config highlight group for Dashboard myself in init.vim after colorscheme, but failed.

**Comment by marko-cerovac** [comment]
I'm currently trying to solve this and I've noticed something weird. Even when I prevent my colorscheme from setting Dashboard colors, I still can't configure highlights from init.vim

For some reason, dashboard just doesn't accept highlight commands from init.vim. I'll keep working on this

**Comment by Young1783** [comment]
From my phenomenon, I think it maybe the the async highlight thread cause this issue, because I can see dashboard with its own highlight for 0.5 second and then turn to material.nvim configuration.

However, I know too little about Lua and maybe one month later, I have time to dig in~~~
FYI, your work is so pretty that I can read codes more pleasantly!
Keep charming~~

**Comment by marko-cerovac** [comment]
Thanks, that means a lot!
I've just moved the dashboard highlights to load as soon as possible. Let me know if you can change the colors now. If you still can't set the highlights, that means it's probably not related to the async loading.

**Comment by Young1783** [comment]
HI~ @marko-cerovac 
After my test, your latest commit did work a bit and see the flash(from original highlight to your theme config) for less time. I think the async loading make this no perfect phenomenon. 

I can add some code in my init.vim and work a bit for me.
```
colorscheme material
autocmd FileType Dashboard hi! link DashboardHeader Boolean
```
But it **does not** work for fist time into Dashboard.

BTW, what is async loading effects? If without async loading, will it take more time to startup?

**Comment by Young1783** [comment]
After trying removing async code, it seems work perfectly even for the first time into dashboard.
And i don't need autocmd anymore. I can config any highlight as I want.
Try it!!!

**Comment by marko-cerovac** [comment]
Ok, that's great. You have found the source of the problem and it does seem to be the async loading.
The async loading is used to improve the start-up time. The most important parts of NeoVim like the background, numbers, borders... get loaded first and the less important things like plugin highlights get loaded later. This speeds up the startup time a lot.
If you want, I can create a new branch which doesn't use async loading. You can then install from this new branch and everything should work fine. Does this solution seem okay to you?

**Comment by Young1783** [comment]
You are so nice.Thanks a lot.

**Comment by Young1783** [comment]
You are so nice.Thanks a lot.

**Comment by marko-cerovac** [comment]
@Young1783 I've created the new branch. It is called no-async and it doesn't use any async loading. If you are using packer.nvim, you can install it using:
```lua
use {
       'marko-cerovac/material.nvim',
       branch = 'no-async'
}
```
or if you are using VimPlug:
```vim
Plug 'marko-cerovac/material.nvim', { 'branch' : 'no-async'}
```
