### ISSUE TITLE
captures changed in nvim-treesitter

### ISSUE THREAD

**Issue by ls4154** [marko-cerovac/material.nvim#194]
> https://github.com/nvim-treesitter/nvim-treesitter/pull/5895 changed the list of admissible capture names to more closely align with upstream tree-sitter and Helix, making sharing/adapting queries easier. This requires changes in colorschemes; see [CONTRIBUTING.md](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md#highlights) and the commit message https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0 for a detailed list of changes. If you cannot adapt your colorscheme (yet), pin nvim-treesitter at v0.9.2.

link: https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1900679583_

**Comment by ls4154** [comment]
It seems this issue has already done in #189
However, some highlights are missing such as `comment.todo`, `comment.hint`

**Comment by marko-cerovac** [comment]
Done. I've added the groups.

**Comment by ls4154** [comment]
Thanks for the update!
However, TODO is displayed as same as a regular comment. 
It would be nice to have different background colors like other tags.

![screenshot-240211-231748](https://github.com/marko-cerovac/material.nvim/assets/26355219/9f9d4462-c0c8-4aa8-ad17-63a1e953267b)
