### ISSUE TITLE
Unable to Remove Bold Text Styling in Neovim Configuration

### ISSUE THREAD

**Issue by itsstillandre** [marko-cerovac/material.nvim#195]
Description:
I've been attempting to configure my Neovim setup using the material.nvim plugin, but I'm encountering an issue with removing the bold text styling for headings and title tags in html.

Reproduction Steps:
    Installed material.nvim plugin using lazy.nvim
    Configured the plugin according to the documentation, specifically targeting the removal of bold text styling.
    Ensured that the configuration settings are correctly applied in my init.lua file.
    Reloaded Neovim to apply the changes.

Expected Behavior:
After configuring the plugin to remove the bold text styling, I expected the text to no longer appear bold in html heading and tags, adhering to the specified configuration settings.

Actual Behavior:
Despite setting the appropriate configuration options to remove bold styling, the text in the html heading and title tags continues to appear bold, indicating that the configuration changes are not being applied as expected.
![image](https://github.com/marko-cerovac/material.nvim/assets/109971408/c34db0ef-5c29-45f7-bcd0-df4876134a6d)

Additional Context:
    Neovim Version: v0.9.5
    My Lazy install of material.nvim:
    return {
    "marko-cerovac/material.nvim",
    config = function()
        require("material").setup({

            contrast = {
                terminal = false,            -- Enable contrast for the built-in terminal
                sidebars = false,            -- Enable contrast for sidebar-like windows ( for example Nvim-Tree )
                floating_windows = false,    -- Enable contrast for floating windows
                cursor_line = false,         -- Enable darker background for the cursor line
                non_current_windows = false, -- Enable contrasted background for non-current windows
                filetypes = {},              -- Specify which filetypes get the contrasted (darker) background
            },

            styles = { -- Give comments style such as bold, italic, underline etc.
                comments = { --[[ italic = true ]]
                },
                strings = { --[[ bold = true ]]
                },
                keywords = { --[[ underline = true ]]
                },
                functions = { --[[ bold = true, undercurl = true ]]
                },
                variables = {},
                operators = {},
            },

            plugins = { -- Uncomment the plugins that you use to highlight them
                "neo-tree",
                "telescope",
                "which-key",
            },

            disable = {
                colored_cursor = false, -- Disable the colored cursor
                borders = false,        -- Disable borders between verticaly split windows
                background = false,     -- Prevent the theme from setting the background (NeoVim then uses your terminal background)
                term_colors = false,    -- Prevent the theme from setting terminal colors
            },

            high_visibility = {
                lighter = false, -- Enable higher contrast text for lighter style
                darker = false,  -- Enable higher contrast text for darker style
            },

            async_loading = true, -- Load parts of the theme asyncronously for faster startup (turned on by default)

            custom_colors = nil,  -- If you want to override the default colors, set this to a function

            custom_highlights = {

            },
        })

        -- Sets the theme style to deep ocean
        vim.g.material_style = "deep ocean"
        vim.cmd("colorscheme material")

       
]]
    end,
}

**Comment by marko-cerovac** [comment]
Sorry for the late reply, I didn't get notified of the issue sooner.

The way you would override this in your config would be:
```lua
local colors = require 'material.colors' -- import the theme colors

require('material').setup {
    -- ... your config ...
    custom_highlights = {
        ['@markup.heading'] = { fg = colors.editor.title, bold = false }, -- use this is you use treesitter
        Title = { fg = colors.editor.title, bold = false }, -- use this if you don't use treesitter
    }
}
```

**Comment by itsstillandre** [comment]
> ```lua
>         ['@markup.heading'] = { fg = colors.editor.title, bold = false }, -- use this is you use treesitter
> ```

That Worked. Thank you
