### ISSUE TITLE
Feature Request: Provide option to highlight diagnostic virtual text

### ISSUE THREAD

**Issue by pwnalone** [marko-cerovac/material.nvim#196]
A lot of colorschemes provide a way to configure the highlighting of diagnostic virtual text. For example, here you can see that Tokyonight highlights the virtual text of the error diagnostics with a faint red background color.

![image](https://github.com/marko-cerovac/material.nvim/assets/3609458/2949244b-8d5d-4970-871a-fa2a90bae1d6)

The highlight groups responsible for this are:

- `DiagnosticVirtualTextHint`
- `DiagnosticVirtualTextInfo`
- `DiagnosticVirtualTextWarn`
- `DiagnosticVirtualTextError`

I opened the [same issue](https://github.com/rebelot/kanagawa.nvim/issues/220) for Kanagawa because it also does not provide an option to highlight the diagnostic virtual text; however, Kanagawa does provide an `overrides` option (similar to Material's `custom_highlights` option), except that `overrides` is a function which takes a `colors` parameter holding the current theme's colors and the color palette and returns a table with the highlight groups to override. This at least provides the ability to add the proper highlighting to diagnostic virtual text by allowing the user to compute at runtime the blend of the text's foreground color and the chosen theme's background.

Ideally, it would be nice to have a simple option to set to `true` to enable highlighting of diagnostic virtual text; however, it would also be sufficient to do something similar to what Kanagawa currently does, by allowing the `custom_highlights` option to be a function that takes a parameter defining the color palette and the current theme's colors. This latter change may be nice to implement regardless, since it would provide users more flexibility in setting custom highlights.

**Comment by pwnalone** [comment]
**UPDATE:**

I just realized that, while `custom_highlights` is not a function, it is still possible to compute the blend of the diagnostic virtual text foreground color and the theme's background at runtime by requiring the `material.colors` module.

![image](https://github.com/marko-cerovac/material.nvim/assets/3609458/3349a811-c9c0-46f2-a071-eafc65492724)

I was able to get it working with the following `lazy.nvim` configuration; however, I still think that it would be nice to make this possible with a simple `highlight_diagnostic_virtual_text` option or similar.

```lua
local rgb_to_hex = function(r, g, b)
  return string.format("#%02x%02x%02x", r, g, b)
end

local hex_to_rgb = function(c)
  c = string.lower(c)
  local r = tonumber(c:sub(2, 3), 16)
  local g = tonumber(c:sub(4, 5), 16)
  local b = tonumber(c:sub(6, 7), 16)
  return { r, g, b }
end

local round = function(val)
  return math.floor(val + 0.5)
end

local clamp = function(val, min, max)
  return math.min(math.max(val, min), max)
end

local blend = function(foreground, background, alpha)
  local bg = hex_to_rgb(background)
  local fg = hex_to_rgb(foreground)

  local blend_channel = function(i)
    return round(clamp(alpha * fg[i] + ((1 - alpha) * bg[i]), 0, 255))
  end

  local r = blend_channel(1)
  local g = blend_channel(2)
  local b = blend_channel(3)

  return rgb_to_hex(r, g, b)
end

local darken = function(color, amount, bg)
  return blend(color, bg or "#000000", amount)
end

return {
  {
    "marko-cerovac/material.nvim",
    version = false,
    lazy = true,
    opts = function()
      local colors = require("material.colors")

      local make_highlight = function(color)
        return { bg = darken(color, 0.1, colors.editor.bg), fg = color }
      end

      return {
        custom_highlights = {
          -- stylua: ignore
          DiagnosticVirtualTextHint  = make_highlight(colors.lsp.hint),
          DiagnosticVirtualTextInfo  = make_highlight(colors.lsp.info),
          DiagnosticVirtualTextWarn  = make_highlight(colors.lsp.warning),
          DiagnosticVirtualTextError = make_highlight(colors.lsp.error),
        },
      }
    end,
  },
}
```

**Comment by marko-cerovac** [comment]
Sure, I'll add it today.

**Comment by marko-cerovac** [comment]
I've updated the theme. The option is added under
```lua
require('material').setup {
    contrast = {
        lsp_virtual_text = true
    }
}
```
I've also added the help functions you used (hex_to_rgb, rgb_to_hex, round, clamp, blend and darken) to the module material.functions so you can use them in your config.

**Comment by pwnalone** [comment]
Hi, thanks for adding this feature. I just pulled the changes to test it out and it seems to be working; however, I believe there is a bug. As you can see in the screenshot, below, diagnostic hints, warnings, and errors are all highlighted as if they are errors.

![image](https://github.com/marko-cerovac/material.nvim/assets/3609458/9403e534-2f3f-465f-bfd9-e61b85d911a7)

I believe the issue is [here](https://github.com/marko-cerovac/material.nvim/blob/552280da5191d49e7fd474d9a39483035c256865/lua/material/highlights/init.lua#L452-L455). It appears that you are setting the foreground color for all diagnostics to `l.error`.

**Comment by marko-cerovac** [comment]
Wow, this was dumb of me to do. I don't know how I've missed this. Thanks for the heads up. Should be fixed now.

**Comment by pwnalone** [comment]
Yup, I just pulled your changes and can confirm that it is working perfectly! Thanks again for implementing this feature. I'll go ahead and close this issue now.
