### ISSUE TITLE
adjust contrast ratio for light background

### ISSUE THREAD

**Issue by matu3ba** [marko-cerovac/material.nvim#2]
For dark backgrounds the color contrast is good, but for light colors its quite bad.

Is there no mathematical model to compute something like this like inverting the gray value to do that?

**Comment by marko-cerovac** [comment]
Well, I was following the material theme palette (https://www.material-theme.com/docs/reference/color-palette/), and the VS Code version of the colorscheme to be true to the original, but I also have noticed the lack of contrast.
I think the best way to go about this is to add a new style like "lighter contrast" which will be a version of the current lighter variant, but with more contrast to make it easier on the eyes.
I think I can get it done in 2-3 days.

**Comment by rti** [comment]
@matu3ba Just to let you know, there is now the possibility to increase the contrast for the light theme.

`vim.g.material_lighter_contrast = true`

A screenshot can be found in PR https://github.com/marko-cerovac/material.nvim/pull/24
