### ISSUE TITLE
Add Support for `CocHighlight{Text,Read,Write}` Highlight Groups

### ISSUE THREAD

**Issue by ewhac** [marko-cerovac/material.nvim#200]
The LSP client in [Coc](/neoclide/coc.nvim/) doesn't use the `LspReference*` highlight groups, but rather its own `CocHighlight*` groups.  Consequently, when the cursor is over a symbol, it doesn't get highlighted when using Coc.

This is arguably a shortcoming in Coc, which should be using the standard highlight group names (the split is kind of understandable -- Coc predates Neovim's integration of LSP support).  Until then, you might care to link the Coc groups to the Lsp groups:

```lua
		CocHighlightText = { link = "LspReferenceText" },
		CocHighlightRead = { link = "LspReferenceRead" },
		CocHighlightWrite = { link = "LspReferenceWrite" },
```

**Comment by marko-cerovac** [comment]
Ok, I've added a new plugin support option to support nvim-coc highlights.
You need to enable it in you config:
```lua
require('material').setup {
    -- ...
    plugins = {
        "coc"
        -- ...
    }
}
```
