### ISSUE TITLE
Broken syntax support for python file.

### ISSUE THREAD

**Issue by kobzar** [marko-cerovac/material.nvim#201]
Hi. Some time ago the python syntax was broken.
I mean that most ow the keywords isn't highlighted like imports, self, vars - e.t.c.

I am use LazyVim and +/- standard configuration of few plugins. 
So, now my code look like this 
<img width="1699" alt="image" src="https://github.com/marko-cerovac/material.nvim/assets/1912842/aa631dfa-c7c3-43fd-915e-f40650770a69">

But, in the same time, another color themes look more usable. For example onne of the most known - tokynoight

<img width="1692" alt="image" src="https://github.com/marko-cerovac/material.nvim/assets/1912842/25eeca55-b7c8-45c9-bc1c-833f3af0d3bd">
(the same +/- in cattpuccin theme)
My configuration for Material theme is default.
I try choose material, material-ocean, change setting but with no luck.

Thanks for the best color theme in world!

**Comment by marko-cerovac** [comment]
An update removed those highlights. Since I don't write any python, I didn't notice the change. It should be fixed now, let me know if there's any more issues.

**Comment by kobzar** [comment]
Very nice. Thank you.
