### ISSUE TITLE
enabling mini in plugins table causes mini.indentscope highlight thingy to not be visible (repro included)

### ISSUE THREAD

**Issue by BeauSLM** [marko-cerovac/material.nvim#208]
repro:

```lua
-- Clone 'mini.nvim' manually in a way that it gets managed by 'mini.deps'
local path_package = vim.fn.stdpath("data") .. "/site/"
local mini_path = path_package .. "pack/deps/start/mini.nvim"
if not vim.loop.fs_stat(mini_path) then
    vim.cmd('echo "Installing `mini.nvim`" | redraw')
    local clone_cmd = {
        "git",
        "clone",
        "--filter=blob:none",
        "https://github.com/echasnovski/mini.nvim",
        mini_path,
    }
    vim.fn.system(clone_cmd)
    vim.cmd("packadd mini.nvim | helptags ALL")
    vim.cmd('echo "Installed `mini.nvim`" | redraw')
end

-- Set up 'mini.deps' (customize to your liking)
require("mini.deps").setup({ path = { package = path_package } })

local add, now, later = MiniDeps.add, MiniDeps.now, MiniDeps.later

add("marko-cerovac/material.nvim")
require("material").setup({
    plugins = {
        -- XXX: comment this out to see scope highlighting
        "mini",
    },
})

require("mini.indentscope").setup()

vim.cmd"colorscheme material"

```

**Comment by marko-cerovac** [comment]
Can you switch the last two lines, so that the ```colorscheme material``` call is executed before ```require('mini.indentscope').setup()``` and let me know the results.
Also, can you please try commenting out ```"mini"``` in the material setup function and let me know if the indent line shows then because I can't reproduce this error.

**Comment by BeauSLM** [comment]
I can no longer reproduce the issue either, with either ordering of the colorscheme and indentscope call  - apologies (on a fresh laptop, perhaps the issue had to do with that). I'll close the issue cause I can't reproduce anymore.

On this working setup I find the markup very difficult to see with the mini colors enabled.

First screenshot is with mini enabled in the material setup, second screenshot is when I comment it out.
<img width="271" alt="image" src="https://github.com/marko-cerovac/material.nvim/assets/63375392/c0fcc08d-1ac5-4c46-ba04-26ba07b0d0dc">
<img width="317" alt="image" src="https://github.com/marko-cerovac/material.nvim/assets/63375392/cd871ae6-6bb0-418c-82c1-3bf77d43d144">

Ig if possible I'd prefer the color be bright like in the second screenshot, but that's a design decision.

**Comment by marko-cerovac** [comment]
Yeah, that's intentional. If you want, you can always override the color in your config. You just need to modify the highlight group ```MiniIndentScopeSymbol```.
