### ISSUE TITLE
Stack traceback error after enabling transpirancy.

### ISSUE THREAD

**Issue by bhaumik-tripathi** [marko-cerovac/material.nvim#212]
I disabled the background in `require("material").setup()` but after doing so, nvim (LazyVim) began to follow the transparency of terminal emulator but giving the following error. I am completely unaware of material's inner workings but I am using it for quiet a long time (and its awesome btw) and this seems to be related to some failing of function calls which were getting correct inputs before the background was disabled. Any help would be appriciated.

Not sure if this is related but after the background was off, the mode indicator(which shows which mode you are in) in lualine with material theme enabled also started having grey font color and not the one it previously had.
I have tried restarting after removing `~/.local/share/nvim`, but that didn't had any effect.

![Screenshot from 2024-10-26 19-10-48](https://github.com/user-attachments/assets/0d18b2e8-4112-46a6-929d-2fb442b92cda)
![Screenshot from 2024-10-26 19-09-59](https://github.com/user-attachments/assets/6798e436-f728-4382-a261-8ade06421037)

```
Error executing vim.schedule lua callback: .../nvim/lazy/material.nvim/lua/material/functions/init.lua:85: attempt to perfor
m arithmetic on a nil value                                                                                                 
stack traceback:                                                                                                            
        .../nvim/lazy/material.nvim/lua/material/functions/init.lua:85: in function 'blend_channel'                         
        .../nvim/lazy/material.nvim/lua/material/functions/init.lua:88: in function 'darken'                                
        ...nvim/lazy/material.nvim/lua/material/highlights/init.lua:452: in function 'fn'                                   
        ...share/nvim/lazy/material.nvim/lua/material/util/init.lua:102: in function ''                                     
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by bhaumik-tripathi** [comment]
Actually, on changing the window to white behind the terminal made me realize that lualine seems broken actually(see right side).
![Screenshot from 2024-10-26 19-30-39](https://github.com/user-attachments/assets/2ef0c4b1-0cdb-4efd-9936-7e37e7b85223)

**Comment by marko-cerovac** [comment]
Can you give me the full material config so that I can reproduce accurately?

**Comment by bhaumik-tripathi** [comment]
Here you go @marko-cerovac ,
```
return {
  {
    "marko-cerovac/material.nvim",
    config = function()
      require("material").setup({
        plugins = {
          "gitsigns",
          "indent-blankline",
          "illuminate",
        },
        disable = {
          background = true,--HERE THE BACKGROUND IS DISABLED TO FOLLOW TERMINAL'S OPACITY AND BACKGROUND.
        },
        contrast = {
          terminal = false, 
          sidebars = true, 
          floating_windows = false, 
          cursor_line = true, 
          lsp_virtual_text = true, 
          non_current_windows = true,
        },
      })
    end,
  },
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "material",
    },
  },
}
```

**Comment by marko-cerovac** [comment]
Okay, it was a bit painful, but I pinpointed the issue.

**Comment by marko-cerovac** [comment]
Okay, it was painful, but I pinpointed the issue. Two config options you set were in conflict. The first one is the ```disable.background```, and the second one is ```contrast.lsp_virtual_text```.

**Comment by marko-cerovac** [comment]
Okay, it was painful, but I pinpointed the issue.
Two config options you set were in conflict.
The first one is the ```disable.background```, and the second one is ```contrast.lsp_virtual_text```.

When the ```lsp_virtual_text``` option is set, the virtual text gets a background that blends with the neovim background.
Example:
1. without ```contrast.lsp_virtual_text```:
![2024-10-31-23:49:25-screenshot](https://github.com/user-attachments/assets/ea1f5d46-8289-43c2-9675-0aaf8041e91e)


2. with ```contrast.lsp_virtual_text```:
![2024-10-31-23:47:17-screenshot](https://github.com/user-attachments/assets/193c42c2-dea8-4315-bdc2-405fa80b66ac)


This hue that this text background has is made by combining the color of the foreground and the color of the background, and meeting them somewhere in between (10% foreground, 90% background).
But if you disable the background with ```disable.background```, what color do we blend the text background with?
I've implemented a workaround that will add the background, but I doubt that it will look good without the default background. My suggestion is that you disable ```contrast.lsp_virtual_text``` if you are going to be disabling the background.

**Comment by marko-cerovac** [comment]
As far as the lualine issue goes, I'll be looking into it tomorrow and will open up a separate issue.

**Comment by bhaumik-tripathi** [comment]
Thanks @marko-cerovac , That fixes the error, the logic seems reasonable. As for the lualine, converting to `stealth` [right one] makes the lualine much better than `default`[left one], (I use LazyVim). Both of them are shown below.
![Screenshot from 2024-11-02 09-40-22](https://github.com/user-attachments/assets/22ba86e1-7944-4ec0-adf4-3e07c385f3b0)

For comparison, I have taken them in white background.
