### ISSUE TITLE
Invalid link on the Material hyperlink

### ISSUE THREAD

**Issue by malklera** [marko-cerovac/material.nvim#213]
On the [README.md](https://github.com/marko-cerovac/material.nvim/blob/main/README.md?plain=1) file.

Line 13.

`The original [Material](https://material-theme.site) theme now available for [NeoVim](https://neovim.io/)`

Line 20.

`A port of [Material](https://material-theme.site) colorscheme for NeoVim written in Lua`

Wrong link(https://material-theme.site)
The page redirects you to buy the domain; it does not seem to be in use anymore.
Looking, the new link seems to be: https://www.material-theme.dev

**Comment by marko-cerovac** [comment]
Thanks for the heads up. Fixed it.
