### ISSUE TITLE
Neogit status - unreadable on hover

### ISSUE THREAD

**Issue by tomaskallup** [marko-cerovac/material.nvim#22]
I'm using the `deep ocean` variant and when I hover over a section in `:Neogit`, it turns into black on black resulting in unreadable text.

https://user-images.githubusercontent.com/26621166/117801456-9adb6a80-b254-11eb-8d1c-dcadacb24e37.mp4

**Comment by marko-cerovac** [comment]
Since I don't use Neogit, I'm not sure exactly what lines of the colorscheme are causing the problem. I've changed the part that I think is causing the problem. If it's not fixed, please let me know, so that I can pinpoint the issue.

**Comment by tomaskallup** [comment]
Perfect, looks way better!
![image](https://user-images.githubusercontent.com/26621166/117951641-a4c4a280-b314-11eb-9c43-e18615aff4a0.png)
