### ISSUE TITLE
[feature request] ability to inject custom colors

### ISSUE THREAD

**Issue by svalaskevicius** [marko-cerovac/material.nvim#30]
hi! this is one nice theme!

is there any way, or can it be implemented, to inject the full custom base colors, instead of just the named presets.

the main reason for the request - I like the `darker` one the most, but I'd like to make it a tad bit darker, more contrasting

**Comment by marko-cerovac** [comment]
Well, I was following the official [material theme palette](https://www.material-theme.com/docs/reference/color-palette/) to be as true to the original as possible so I never thought it would be necessary to change the color values. Of course, since there is a need, I will try to implement it. I will probably take a few days, but I'm pretty sure I can make it work.

**Comment by svalaskevicius** [comment]
Thanks! So far I came up with https://github.com/svalaskevicius/material.nvim/blob/b6e0241348eb81a17b5e85a17b3dbf2ea1343de8/lua/material/colors.lua#L46 (in combination with a teal variable colour) but I'm sure I'll be editing the shades as I code using it more :)

**Comment by rti** [comment]
@svalaskevicius Thanks a lot for opening this issue. I thought about exactly the same thing as well already.

@marko-cerovac Great that you want to take a look into it. Thank you. When I thought about how to implement it I started to like the idea of a `setup()` function to init the plugin - as many other nvim lua plugins use it as well. Is there any reason material.nvim does not have such a function? I think it would be even simpler (and more common) to provide this function with a color map (and other config parameters).

Let me know if I can be of any help.

**Comment by marko-cerovac** [comment]
In the beginning, I also thought about implementing it with a setup function, but there is a problem. Unlike colorschemes, other plugins get loaded only once and they can be called from the setup function. It basically tells the plugin "load up with these settings". But with colorschemes, what happens when you switch to a different colorscheme and then back to material using the command ``` :colorscheme material ``` , or when you use the ```toggle_style()``` function? The whole plugin needs to be loaded again, but this time, you didn't pass it any setup parameters and it would just use the defaults, and not your custom settings. The most logical way to solve this is to use global variables, which don't go away even if you switch to another colorscheme.

**Comment by rti** [comment]
Thanks for the explanation. I think I still do not really understand why we cannot have a setup function though. But I never wrote a vim plugin nor wrote a serious amount of lua. So please excuse me if I am on a completely wrong path.

If we take for example [lualine](https://github.com/hoob3rt/lualine.nvim): It creates a variable `config` [here](https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine/init.lua#L8) which actually just points to the [config object in the config module](https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine/config.lua#L3). On `setup`, lualine [sets the given user config](https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine/init.lua#L182) which in turn [stores it in the config object of the config module](https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine/config.lua#L32). Autocmds call a `statusline()` function whenever e.g. a [buffer is entered or left](https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine/init.lua#L172) (not only duing `setup`) and this `statusline()` function relies on [values from the config object](https://github.com/hoob3rt/lualine.nvim/blob/master/lua/lualine/init.lua#L53).

Isn't this basically the same thing we would need? Query the config object for color values and other settings as soon as `toggle_style()` is called at any point during editor runtime?

**Comment by marko-cerovac** [comment]
I guess it can be done, and I also like setting up plugins with setup functions and I think it looks really clean, but we need to weigh the pros and cons here. Global variables are meant to be used for this kind of stuff, and if you type ```:let g:``` and then hit tab to autocomplete, you will see that a lot of plugins use it exactly for this kind of configuration (indent-blankline, nvim-tree, dashboard, vsinp and many more..). They don't cause any performance issues for NeoVim and make writing plugins much easier. And the biggest issue is backwards compatibility. If I were to implement it, hundreds of users of this colorscheme would get errors after an update. I would have to make a in-between solution for a while where the theme would use global variables or a setup function to prevent it breaking for users, and that would be a really huge mess. The custom color injection can be solved pretty easily with a global table like in [tokyonight.nvim](https://github.com/folke/tokyonight.nvim). Also a majority of users still uses vim-script for configuration and don't plan on switching to lua. This makes the theme a lot more friendly and easier to configure for them. I'm sorry, but I just don't see any major reason to switch to a setup function, and the drawbacks are really big.

**Comment by rti** [comment]
You are right. Especially the backwards compatibility is a huge issue with setup function.

Sorry @svalaskevicius for hijacking your issue thread here.

**Comment by svalaskevicius** [comment]
Absolutely no problems for continuing the conversation! (from my side at least :)). I'm very new to this lua style plugins and themes so I don't have much input myself. 

This ticket is merely an idea I had, for the author of the theme to look at, consider and decide :)

To add, I'm happy with any outcome, worst case I can periodically refresh my fork from here and have my adjusted colours that way - so just a question of convenience :)

Also thanks to @marko-cerovac for considering this idea!

**Comment by svalaskevicius** [comment]
Thanks!

**Comment by svalaskevicius** [comment]
I've enabled it and it's working fine - will close the issue :)
