### ISSUE TITLE
What's the colored cursor line at the head of some line. And how to config this feature.

### ISSUE THREAD

**Issue by cstsunfu** [marko-cerovac/material.nvim#38]
<img width="189" alt="截屏2021-06-03 下午5 11 41" src="https://user-images.githubusercontent.com/24812659/120620123-3bf1c580-c48f-11eb-854e-46f6a6e47226.png">
<img width="335" alt="截屏2021-06-03 下午5 08 20" src="https://user-images.githubusercontent.com/24812659/120620127-3f854c80-c48f-11eb-8347-4d3d6180e09b.png">
Thanks for your awesome job.

**Comment by marko-cerovac** [comment]
Thanks for the compliment :smile: 

The blue and green lines are git indicators. The green lines are the added lines, and the blue ones are the modified lines.
I use [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) for git integration. Just follow the readme on their github page and it will work perfectly.

**Comment by cstsunfu** [comment]
> Thanks for the compliment 😄
> 
> The blue and green lines are git indicators. The green lines are the added lines, and the blue ones are the modified lines.
> I use [gitsigns.nvim](https://github.com/lewis6991/gitsigns.nvim) for git integration. Just follow the readme on their github page and it will work perfectly.

Thanks for your reply.
