### ISSUE TITLE
Disable tilde at end of buffer

### ISSUE THREAD

**Issue by DanKGooGLy** [marko-cerovac/material.nvim#39]
Option to disable the tildes "`~`" at the empty of end of a buffer.  
If you don't know what I'm talking about, here's a picture:
![image](https://user-images.githubusercontent.com/34890978/122147535-19649280-ce27-11eb-918a-89dff3af984a.png)

**Comment by marko-cerovac** [comment]
Sure, I'm adding it right now

**Comment by marko-cerovac** [comment]
It's done, you can now set the variable ```vim.g.material_hide_eob = true``` to disable the end of buffer lines.
I've also added a function that you can call or bind to a key, to toggle the lines on and off without the need to restart neovim.
An example of this would be:
```nnoremap <leader>me :lua require('material.functions').toggle_eob()<CR>```

**Comment by DanKGooGLy** [comment]
Alright, thanks.
