### ISSUE TITLE
LSP Diagnostics use the wrong groups

### ISSUE THREAD

**Issue by folke** [marko-cerovac/material.nvim#4]
> LSP Groups (descriptions and ordering from `:h lsp-highlight`)

Multiple highlight groups have the wrong for LSP diagnostics.

For example:
* `LspDiagnosticsError` should be `LspDiagnosticsDefaultError`.
* `LspDiagnosticsErrorFloating` should be `LspDiagnosticsFloatingError`.

![image](https://user-images.githubusercontent.com/292349/114376844-dd693480-9b3a-11eb-88e7-86fcf582a4bf.png)

**Comment by marko-cerovac** [comment]
Thanks for pointing it out, I've fixed it now and added a new option.
You can now turn on and off the underline for Lsp messages by setting the global g:material_lsp_underline to 1 or 0
