### ISSUE TITLE
[Question] Transparent background

### ISSUE THREAD

**Issue by kornicameister** [marko-cerovac/material.nvim#40]
Hello @marko-cerovac.
I've been playing around with some settings here but couldn't exactly make a background transparent using your theme. Do you have any hints how this can be achieved?

**Comment by marko-cerovac** [comment]
Sure, You just need to set ```vim.g.material_disable_background = true```. This will prevent the theme from setting the background, which means that neovim will use the background of your terminal. So, if you want a transparent background, you also need to make the terminal background transparent

**Comment by kornicameister** [comment]
Well, that's the thing. I have that setting in place. Here's my entire section for it.
I've tried setting that up when plugin loaded (i.e. packer), setting that up at the end of `config/nvim/init.lua` but neither helped.

```
opt.termguicolors = true
opt.background = "dark"

g.material_style = "darker"
g.material_disable_background = true
g.material_italic_comments = false

require("material").set()
```

As you can see here:
![image](https://user-images.githubusercontent.com/1029674/122982416-217a8000-d39b-11eb-880f-5174d7266ef7.png)
I do have a transparent backroundd for terminal. But background in `nvim` behaves rather odd. It is transparent below `lualine` but totally black above it. Also if terminal resizes a transparent background can be seen but once `nvim` redraws it is lost once again.

**Comment by kornicameister** [comment]
Just found the issue:
```
    {
      "sunjon/shade.nvim",
      config = function()
        require("shade").setup({
          overlay_opacity = 75,
        })
      end,
    },
```

Looks like https://github.com/sunjon/Shade.nvim was the source of the issue :/.
Wonder why though. Anyway, closing it since the root cause was outside of the theme.

Cheers! :D

**Comment by marko-cerovac** [comment]
@kornicameister Nice, I would have never guessed that. I guess that the shadung works by going through your colors and darkening the rgb values every time you change a window, so it doesn't know how to behave when a background isn't set.
