### ISSUE TITLE
Oceanic differs from the screenshot

### ISSUE THREAD

**Issue by fuelen** [marko-cerovac/material.nvim#42]
This is what I've got:
![image](https://user-images.githubusercontent.com/588762/124907349-b5ca2100-dff0-11eb-9c68-4093c62324b1.png)
low readability in nvim-tree, comments and virtual text

**Comment by marko-cerovac** [comment]
I've changed the comments and nvim-tree files color. It should be more visible now, and look the same as in vscode. Let me know if there's any more issues or suggestions.

**Comment by fuelen** [comment]
@marko-cerovac much better now, thanks.

**Comment by fuelen** [comment]
Another suggestion I have is not related to the current issue, but anyway, it would be great to have visual separators between splits. I'm not sure if it is doable because of another background for nvim-tree, but this is how my current theme looks:
![image](https://user-images.githubusercontent.com/588762/125188795-d804ae80-e23d-11eb-8c56-4188483a18ec.png)

**Comment by marko-cerovac** [comment]
@fuelen This is an option. If you put
```vim.g.material_borders = true```
 in your config, the borders will be enabled. This one, and all the other options are in the README
