### ISSUE TITLE
Simple way to override applied theme colors [Feature request/Question]

### ISSUE THREAD

**Issue by AndreAugustoAAQ** [marko-cerovac/material.nvim#43]
Would it be possible to implement a way to easily replace the theme colors of specific elements? Without using the highlight option directly, and in lua to facilitate
Something like:
```lua
				rgb      cterm  string
local color = {'#ffffff', 255, 'color-name'}
material.custom_highlight('ELEMENT', {bg="#fff" fg=color})
```
Or if something like this already exists, how could I do it?
I'm currently using a hack with autocmd to change colors but I don't feel it's good enough

**Comment by marko-cerovac** [comment]
For now, there is a way to change the built-in colors. For example if you don't like the shade of blue that the colorscheme uses, or the comments color, you can set them yourself. Just add :
```
vim.g.material_custom_colors = {
    blue = '#0000FF',
    comments = '#0A0A0A'
}
```
By doing this, you can change the colors defined in [lua/material/colors.lua](https://github.com/marko-cerovac/material.nvim/blob/main/lua/material/colors.lua).

I will be adding an option to change highlights one of these days.

**Comment by marko-cerovac** [comment]
@AndreAugustoAAQ  the theme now uses a setup function instead of global variables for configuration. There is a new option to set your own highlights. The instructions are in the README.  It works almost exactly like the solution that you suggested.
