### ISSUE TITLE
Context indent not highlighted for indent-blankline in darker style

### ISSUE THREAD

**Issue by gbcreation** [marko-cerovac/material.nvim#47]
When the darker style is selected, the indent line displayed by the indent-blankline plugin is not "highlighted" for the current context.

The `IndentBlanklineContextChar` highlighting has the same color as the `IndentBlanklineChar` one. Could you please specify a different color for `IndentBlanklineContextChar` to make the context more visible?

**Comment by marko-cerovac** [comment]
I didn't notice that until now, thanks for pointing it out. I fixed the color. Let me know if there's any more issues.

**Comment by gbcreation** [comment]
Works perfectly. Thank you!
