### ISSUE TITLE
High contrast mode for the darker style

### ISSUE THREAD

**Issue by gbcreation** [marko-cerovac/material.nvim#48]
It would be nice to have a high contrast mode for the darker style. Currently, line numbers and code comments aren't easy to read.

**Comment by marko-cerovac** [comment]
I've added the higher contast option. Just use ```let g:material_darker_contrast=v:true``` in your init.vim

**Comment by gbcreation** [comment]
Thank you very much. That's much better.
Could you also set a higher contrast for windows' borders?
