### ISSUE TITLE
split sidebar bg and float bg

### ISSUE THREAD

**Issue by vod3** [marko-cerovac/material.nvim#49]
Hello,
It would be great to have an option to define a separate background-color for each the sidebar and the float popup.

For example, I like to have my tree on the left to have the same color as my normal editview, but the floating popup on DEEP OCEAN is barely distinguible from the edit view.

Thanks for this great colorscheme!

**Comment by marko-cerovac** [comment]
Sure, I'll look into adding this option one of these days.

**Comment by marko-cerovac** [comment]
I will move the whole theme config to a setup function, rather than using global variables. When I do this, the background colors will be easy to implement. It should be done in a couple of weeks.

**Comment by marko-cerovac** [comment]
@vod3  it's done. The theme is now configured trough a setup function instead of using global variables. This way, I've added the option to specify which filetypes get the darker background. The instructions are in the README.
