### ISSUE TITLE
Terminal colors

### ISSUE THREAD

**Issue by jonathf** [marko-cerovac/material.nvim#50]
I am impressive with the extensivness of how many attribute this theme covers. Well done.

I like that the colors of the terminal emulator is set using `vim.g.terminal_color_NN`, but don't like that the 0-7 and 8-15 are the same colors.

I tried to manually set the colors in my rc, but ecause of the variables are set in async part of the code, it is not yielding the result I was looking for. Would it be possible to allow for a workaround for this? Either:

1. Update the theme to differentiate between the 0-7 and 8-15.
2. Add a global flag disabling setting the terminal colors (so the user can set them manually)
3. Allow for user to provided terminal colors through some setup argument (or global variable).
4. Move setting the terminal colors in the main thread.

If any of these options seem reasonable to you, I will gladly contribute with a PR.

**Comment by marko-cerovac** [comment]
Sure, all of these seem reasonable. I will implement the changes tonight or tomorrow.

**Comment by marko-cerovac** [comment]
@jonathf I've changed the terminal colors. The colors 0-7 are now 10% darker. I have also added an option to disable the theme from setting the terminal colors, so that you can define your own. The option is called ```vim.g.material_disable_terminal```. If there's any more issues, just let me know :wink:

**Comment by jonathf** [comment]
Works great! Thanks.
