### ISSUE TITLE
Startup error in lua due to unitialized config.options table

### ISSUE THREAD

**Issue by f0rki** [marko-cerovac/material.nvim#54]
I get the following error on startup

```
E5108: Error executing lua ...plugged/material.nvim/lua/material/colors.lua:55: attempt to index field 'text_contrast' (a nil value)
```

I believe this is because the table in `lua/material/config.lua` is not initialized, so any `require('material/config')` gives you a table without the defaults (including the nested tables). A call to `setup` in `config.lua` has fixed this for me:

```lua
Config.setup()
return Config
```

I am using

```
$ nvim --version
NVIM v0.5.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
...
```

and I am loading the theme in my `init.vim` without any lua configuration of the colorscheme. I do configure lualine with the material theme though.

```vim
let g:material_style = 'darker'
colorscheme material
```

**Comment by marko-cerovac** [comment]
Oh, I didn't notice that. Yeah, since the setup function never gets called, the table is set to nil. It should be fixed now. Let me know if the problem is still there.

**Comment by f0rki** [comment]
works now. thanks!
