### ISSUE TITLE
Re-implement custom colors feature

### ISSUE THREAD

**Issue by camiloaromero23** [marko-cerovac/material.nvim#56]
It's been a while since this feature is in a TODO and I miss it a lot to change my accent color.

**Comment by marko-cerovac** [comment]
The last time I've tried to implement it, it was giving me errors, so I decided to leave it out for now. I will try again today.

**Comment by marko-cerovac** [comment]
@camiloaromero23 You can use costom_colors variable to change the accent color.
Just use 
```lua
custom_colors = {
    accent = '#FF00FF' -- or whatever color you like
}
```

**Comment by camiloaromero23** [comment]
I had that option commented out waiting for the re-implementation. Thanks a lot for your great work man!

**Comment by camiloaromero23** [comment]
The `custom_colors` table stopped working (I guess you commented out the feature in [colors.lua line 249](https://github.com/marko-cerovac/material.nvim/blob/6787952b33fe221e2fce73399b2e6eaad3616780/lua/material/colors.lua#L249).

Correct me if i'm wrong

**Comment by marko-cerovac** [comment]
I removed the option because I was planing on working on it. I wanted to add the possibility of injecting custom colors into the custom_highlights table, so that you can have something like this in you config
```lua
require('material').setup {
    -- ... your config

    custom_colors = {
        my_cool_color = '#ABABAB'
    },
    custom_highlights = {
        CursorLine =  { fg = my_cool_color }
    }
}
```

I'll implement it in the next few weeks.
For now, I've put the option back for now, so that you can use it. It works the same way as before but it isn't in the README or the help docs.

**Comment by camiloaromero23** [comment]
Nice. But this new feature will not override the possibility of overriding theme colors right?

**Comment by marko-cerovac** [comment]
It won't. It will work just as before, but with this added functionality.

**Comment by camiloaromero23** [comment]
I'll close the Issue then. Thanks for your great work man!
