### ISSUE TITLE
[Question] gruvbox-material ?

### ISSUE THREAD

**Issue by devalkyrie** [marko-cerovac/material.nvim#66]
Is there a gruvbox-material variant ?
(like, https://github.com/sainnhe/gruvbox-material)
if not, can someone guide me on the resources required to implement it. Thanks !

**Comment by marko-cerovac** [comment]
The material colorscheme is a whole different theme. This plugin follows the [original theme](https://material-theme.com/).
The dark variant of this theme resembles gruvbox, but the gruvbox-material is a part of the gruvbox theme, not material.
The only gruvbox-material theme that exists for neovim currently is https://github.com/sainnhe/gruvbox-material
