### ISSUE TITLE
Custom_highlights not working

### ISSUE THREAD

**Issue by dodonut** [marko-cerovac/material.nvim#68]
The following is my whole config on the theme. Everything works fine, I just want to set some colors because they blend too much on my monitor... 
![image](https://user-images.githubusercontent.com/19748045/144286409-938a9423-3e1f-44f4-9f92-b88d32ce9ff9.png)

I've put this config on LineNr to show that is not working, this hex should mean red but any color that I put, turns out white. That happens on the other config mentioned on readme as well... I've tested the other themes, and seem that is not applying the colors or the custom_highlights erase and leave the default value, idk.

Other thing, what are all the custom highlights that I can put there? I did not found on the doc and looking in the code (not understanding much) could not find a reference... could you add on the doc please?

**Comment by dodonut** [comment]
I've found the answer on the other issues, but the lack of documentation still stands. Great plugin!!!

**Comment by marko-cerovac** [comment]
@dodonut  I've added the documentation for custom_highlights. The reason it was never well documented is I wanted to extend the functionality and just can't seem to get around to do it. I was planning on writing good documentation after I implement everything. But I'll do it one of these days for sure :smile: .
