### ISSUE TITLE
[Question] How to use custom_highlights

### ISSUE THREAD

**Issue by dodonut** [marko-cerovac/material.nvim#69]
Is it possible to change the color of the comments? I would like the color green or a bright one, because they blend too much with my monitor. Also, could I change the color of a certain word? I would like the work 'TODO' to be yellow or something like that to get more attention. Thanks.

**Comment by marko-cerovac** [comment]
The documentation on the custom_highlights table is in the README, as well as in the docs under ```:help material.nvim-configuration```
As far as the comments go, there are who groups that set them.
One is Comment (the standard neovim comment group).
And the other one is TSComment (the tresitter comment highlight group)
If you are using treesitter, you should change this one.
The TODO keyword is already highlighted in yellow, but if you want to customize it, the group name is: Todo.

Here is an example
```lua
require('material').setup{
	custom_highlights = {
                TSComment= '#00FF00',
		Todo = '#FFFF00'
	}
}
```

**Comment by dodonut** [comment]
Thanks a lot, just a fix, should be an object.
`require('material').setup{
	custom_highlights = {
		LineNr = { fg = colors.white },
                TSComment= { fg = '#00FF00' },
		Todo = { fg = '#00FF00' }
	},

}`

**Comment by noxx** [comment]
But if we wanted to make the custom highlight a color that is already defined in "material.nvim/lua/material/colors.lua", for example: I want to set LineNr = { fg = darkred } but darkred is defined in the path above as '#DC6068', yet i dont have acces in my  require('material').setup to that darkred. Is there an easy way of refrencing that color, or shuold i just manually write it as a hex value to my setup

**Comment by noxx** [comment]
local colors = require "pack.packer.start.material.nvim.lua.material.colors" , i have tried doing this, but the problem is, lua require function doesn't sees material.nvim as material/nvim, so it can't find the directory. Is there an easier solution then rewriting luas require function. Thanks

**Comment by marko-cerovac** [comment]
@noxx nema potrebe za cijelom putanjom. Samo stavi
```lua
local colors = require('material').colors
```
i onda kasnije
```lua
custom_highlights = {
    LineNr = { fg = colors.red }
}
```
Pozdrav

**Comment by noxx** [comment]
@marko-cerovac Pomesao si definisanje colors, ali pogledao sam malo po source kodu i provalio sam treba da se stavi 
`local colors = require('material.colors')`
