### ISSUE TITLE
Wrong background color with the latest commit

### ISSUE THREAD

**Issue by huyvohcmc** [marko-cerovac/material.nvim#7]
I just ran plugin update for my local nvim and noticed the background color (or more) of "deep ocean" is wrongly displayed.
<img width="1440" alt="Screen Shot 2021-04-17 at 8 35 33 PM" src="https://user-images.githubusercontent.com/17645203/115115055-817c3100-9fbc-11eb-85eb-726203f14f05.png">

I then changed `material.nvim` and `colorbuddy` installation to these commits:
```lua
  use {
    'tjdevries/colorbuddy.nvim',
    commit = 'cb9e044ebf0b690a56ebb4018cf300703f8dbec1'
  }
  use {
    'marko-cerovac/material.nvim',
    commit = '4ea2318b495ae1da5fa3fb96fe90992efcf54988'
  }
```
and the color was fine again:
<img width="1440" alt="Screen Shot 2021-04-17 at 8 38 22 PM" src="https://user-images.githubusercontent.com/17645203/115115140-e20b6e00-9fbc-11eb-83cb-05e1a84e1252.png">

**Comment by marko-cerovac** [comment]
The same thing happened to me also, it seems to be an issue with the latest update of colorbuddy.nvim.
I'm looking into solving it right now.

**Comment by marko-cerovac** [comment]
I think I've managed to get to the source of the problem, and I'm positive it's an issue withe the latest colobuddy commit.
The guibg gets the name of the background variable assigned to it instead of the value.
I've opened up an issue on the colorbuddy.nvim repo, and it should be resolved pretty soon.

**Comment by marko-cerovac** [comment]
It should be resolved now
