### ISSUE TITLE
Wrong Diagnostic Colors in LuaLine

### ISSUE THREAD

**Issue by iloverink** [marko-cerovac/material.nvim#70]
The inline and sign column colors for diagnostics look correct, however the colors in lualine seem to be defaulting to colors outside the theme.

![image](https://user-images.githubusercontent.com/47754304/145292068-6e979dfd-0a79-48d0-890a-ed3e783bb017.png)

**Comment by marko-cerovac** [comment]
The lsp colors that lualine used for those icons were loading asynchronously, so lualine loaded the them before they were set. I've fixed it now, it should be working just fine.
Btw, I'm working on a major update to the theme, and I will be adding one more lualine theme, so stay tuned :smiley:
