### ISSUE TITLE
nvim-cmp support

### ISSUE THREAD

**Issue by axieax** [marko-cerovac/material.nvim#72]
Hello!
[nvim-cmp](https://github.com/hrsh7th/nvim-cmp) now has [kind highlights](https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#how-to-add-visual-studio-code-dark-theme-colors-to-the-menu). Would it be possible to add support for this (as well as CmpItemAbbrDeprecated)? It shouldn't be too difficult - something like what [Dracula](https://github.com/Mofiqul/dracula.nvim/blob/a8106b9370338fbec149236132fd0861d5bb6265/lua/dracula/init.lua#L375-L408) does with links should be fine :)
Thanks!!

**Comment by marko-cerovac** [comment]
Yes, I've been working on some major improvements to the theme in the last week. Among them is the nvim-cmp kind highlights. I will push the changes in two on three days, so stay tuned.

**Comment by axieax** [comment]
Looking forward to them!
