### ISSUE TITLE
Issue with vim-illuminate

### ISSUE THREAD

**Issue by RayZ0rr** [marko-cerovac/material.nvim#74]
I have the following in vim-illuminate

```lua
vim.cmd[[
augroup illuminate_augroup
    autocmd!
    autocmd VimEnter * hi illuminatedCurWord cterm=italic gui=italic
    autocmd VimEnter * hi illuminatedWord cterm=underline gui=underline
augroup END
]]
```
and material settings :
```vim
let g:material_style = 'deep ocean'
colorscheme material
```

But I am not getting italic words when I place cursor on a word with multiple occurrences. I also don't get underline.

For example this file:-

```bash
#!/usr/bin/env bash

# find "${1}" -maxdepth 1 -not -path "${1}" -type d -printf "%f\n"
# find "${1}" -maxdepth 1 -not -path "${1}" -type d -print0
readarray -d '' myArray1 < <(find "${1}" -maxdepth 1 -not -path "${1}" -type d -printf "%f\n")
readarray -d '' myArray2 < <(find "${1}" -maxdepth 1 -not -path "${1}" -type d -print0)
echo "myArray1\n"
for i in "${myArray1[@]}" ; do
	echo "$i "
done
echo "myArray2\n"
for i in "${myArray2[@]}" ; do
	echo "$i "
done
```
![material-illuminate1](https://user-images.githubusercontent.com/96843787/149534798-fad0e360-7e42-4644-9366-486c72c743ce.png)
![material-illuminate2](https://user-images.githubusercontent.com/96843787/149534810-cefca05f-57ef-46e3-bcd0-3a4b52f43b94.png)

**Comment by marko-cerovac** [comment]
One of the main features of material.nvim is it's async highlight loading, which means that your NeoVim startup time is reduced significantly when using this theme. But it also means that custom highlight commands often won't work. This is why there is an option in the setup function called custom highlights. So to make your setup work, I would suggest something like this:
```lua
require('material').setup({
     custom_highlights = {
        illuminatedCurWord = { gui = 'italic' },
        illuminatedWord = { gui = 'underline' }
    }
})
```
