### ISSUE TITLE
Italics not working

### ISSUE THREAD

**Issue by notjl** [marko-cerovac/material.nvim#77]
![image](https://user-images.githubusercontent.com/58279268/152015004-6e96b54d-c399-45ec-a3a4-39260a8724b6.png)
I have it configured to have italics on comments but as you can see it's not working

**Comment by marko-cerovac** [comment]
I also use a very similar config for my setup and it works just fine for me, so it can't be a issue with the comment highlight. I also tried to troubleshoot without treesitter and it also worked just fine. I see that your functions and keywords also aren't italic. This leads me to believe that your config isn't being loaded for some reason. I't could be an issue with the if statement surrounding the config. Have you tried removing it to check if everything works then?

**Comment by marko-cerovac** [comment]
There are a couple things wrong with your config.
+ First, the expression ```colorscheme == 'material'``` is invalid.
There is no variable called material.
That's why the setup function never gets called.
If you look closely, functions and keywords aren't italic as well, even tho you set them to italic.
That's because the IF statement gets evaluated as false every time.
The "deep ocean" variant is set because you set it before the IF statement.
The correct way to do this would be
```if vim.g.colors_name == 'material then ...'```

+ Second, the setup function should be called **before** the colorscheme is set to material,
Your IF statement is meant to check if the colorscheme is already set to material, and then call the setup function if it is.
This won't do anything. You first need to call the setup function, and then set ```colorscheme material```

**Comment by notjl** [comment]
I forgot to remove the initial `g.material_style = 'deep ocean'`, my bad.

This is how my configuration looks like even before issuing the problem. `contrast` options work, the style works, I'm not sure how `high_visibility` works but it seems it doesn't. Then there's `italics`, not working too. To give context on what's happening on my config (I also removed the initial `g.material_style` before having read your guidance):
```lua
local colorscheme = 'material'
local cmd = vim.api.nvim_command
local g = vim.g

local colo_ok, _ = pcall(cmd, "colo " .. colorscheme)
if not colo_ok then
    vim.notify('Colorscheme ' .. colorscheme .. ' not found!')
    return
else
    -- Tokyonight
    if colorscheme == 'tokyonight' then
        g.tokyonight_style = 'night'
        g.tokyonight_italic_functions = true
        g.tokyonight_italic_comments = true
        g.tokyonight_italic_keywords = true
    end

    -- Material
    if colorscheme == 'material' then
        g.material_style = 'deep ocean'
        require('material').setup({
            contrast = {
                sidebars = true,
                floating_windows = true,
                non_current_windows = true,
                popup_menu = true
            },
            italics = {
                comments=true,
                functions=true,
                keywords=true
            },
            high_visibility = {
                darker = true
            },
        })
        -- notify if setup is loaded
        vim.notify('Material and Setup loaded!', 'info', {render='minimal'})
    end

    -- re-require
    cmd('colo ' .. colorscheme)
    vim.notify('Colorscheme loaded!', 'info', {render='minimal'})
end
```
Looking at my notifications,
![image](https://user-images.githubusercontent.com/58279268/152129380-02c8631a-d11b-4dad-a4b6-a5853375434d.png)

I even tried putting the setup function outside the if statement, to no avail.

**Comment by marko-cerovac** [comment]
Okay, this is really weird. I'm looking into it right now.
Do you use treesitter?

As far as the ```high_visibility``` goes, setting this to true boosts contrast for the style that you set it for.
Some users had issues with the visibility on the lighter and darker style, so I added this in.
This is the lighter style with high_visibility set to false:
![lighter-default](https://user-images.githubusercontent.com/76592799/152159336-c5af977a-f793-4359-bfd4-09ee12071553.png)

And this is when it is set to true:
![lighter-contrast](https://user-images.githubusercontent.com/76592799/152159340-27d6e1e9-4789-4ed4-bfef-e0b7ef0c3dbf.png)

**Comment by marko-cerovac** [comment]
Update:
I just replaced your config with mine, and I also got the same issues.
This confirms that is is an issue with your config.
Contrast options also don't work.
Please try to call the setup function before setting ```colorscheme material```, and let me know if it works.

**Comment by marko-cerovac** [comment]
Okay great. A good option is to use lazy-loading if you use packer.nvim. I load material.nvim on startup, and tokyonight.nvim and nord theme get loaded only when I call the ```:colorscheme``` command.
