### ISSUE TITLE
Packer Sync fails to update

### ISSUE THREAD

**Issue by Huray-hub** [marko-cerovac/material.nvim#79]
![image](https://user-images.githubusercontent.com/47453979/154055167-9494f5fd-62c2-443a-bb1e-31e3bd98ae3e.png)

**Comment by marko-cerovac** [comment]
Well, it seems that you made some local changes to the theme. Packer won't override them, so it doesn't update. If you remove the changes that you made or delete the theme directory,.t should be fixed.

**Comment by Huray-hub** [comment]
Indeed I have made a small change I forgot about. Commented out code + reinstall fixed the issue. Thank you!
