### ISSUE TITLE
Special character highlights

### ISSUE THREAD

**Issue by jacksonludwig** [marko-cerovac/material.nvim#80]
I noticed `Special`/`SpecialChar`/`cTSStringEscape` and related highlights are quite dark as shown below in the `darker` variant:
![image](https://user-images.githubusercontent.com/42984254/154720420-ffdd1576-2409-4716-a621-9dbed688f000.png)

This is an easy change for the user to make, but I thought it could make sense to change the default to be more visible, as currently it's quite hard to see in my opinion. In fact, I would make it some sort of bright or colorful highlight since "Special" things are rare.

**Comment by marko-cerovac** [comment]
You are right, I've made them a little bit more visible. Thanks for the input.
