### ISSUE TITLE
Color of `terminal_color_8` should be darker

### ISSUE THREAD

**Issue by loichyan** [marko-cerovac/material.nvim#82]
I found that when I use zsh in neovim, the autocomplete color is too bright and I noticed that the problem is caused by `terminal_color_8` which usually means `grey` in terminal palette.
The default color:
![2022-03-10 09-49-42 的屏幕截图](https://user-images.githubusercontent.com/73006950/157572330-2c83f850-445c-4bd6-84ae-5c3202f68979.png)
After setting to a darker color (`colors.disable`):
![2022-03-10 09-50-09 的屏幕截图](https://user-images.githubusercontent.com/73006950/157572461-8d3e0dc8-dd7f-4a25-9b69-eda5f910b7a7.png)

**Comment by marko-cerovac** [comment]
Good idea, I've implemented the change. Thanks for the input :smile:

**Comment by loichyan** [comment]
Many thanks!
