### ISSUE TITLE
DiffText not visible

### ISSUE THREAD

**Issue by David-Kunz** [marko-cerovac/material.nvim#85]
Hi 👋 ,

Thanks for this great colorscheme! 

I just noticed that when diffing files, it's really hard to see the changed text within a changed line (`DiffText`).

For me, the following works great (at least for dark variants):

```lua
require('material').setup{
	custom_highlights = {
		DiffText = { bg = '#000000' }
	}
}
```

Maybe you want to adapt the default value a bit?

Thanks and best regards,
David

**Comment by marko-cerovac** [comment]
I've changed the background to give it a little bit more contrast (the same color that NvimTree has when you turn on contrast).
If you still have issues with visibility, please let me know.
And thank you for your YouTube videos, they are really helpful. I learned about nvim-dap and configured it from watching your videos :smile:

**Comment by David-Kunz** [comment]
Hey @marko-cerovac ,

Thanks a lot for this quick change, it works perfectly 🥇 .

And thanks for this nice comment regarding my videos :)

Best regards,
David
