### ISSUE TITLE
Italics set up doesn't work

### ISSUE THREAD

**Issue by ChavaTI** [marko-cerovac/material.nvim#89]
Everything works fine except the italic fonts. I don't know if I need a special font for this or maybe my setup is not correct.

```lua
local material = require 'material'

vim.o.termguicolors = true
vim.g.material_style = 'darker'

material.setup({
  contrast = {
    sidebars = false,
    floating_windows = false,
    line_numbers = true,
    sign_column = false,
    cursor_line = false,
    non_current_windows = false,
    popup_menu = false
  },
  italics = {
    comments = true,
    strings = false,
    keywords = true,
    functions = true,
    variables = false
  },
  contrast_filetypes = {},
  high_visibility = {lighter = false, darker = false},
  disable = {
    borders = false,
    background = true,
    term_colors = false,
    eob_lines = false
  },
  custom_highlights = {}
})

vim.cmd 'colorscheme material'
```

**Comment by marko-cerovac** [comment]
Your config seems fine. The issue has to be somewhere else. What font are you using? And could you please post a screenshot of some code where the italics should be.

**Comment by ChavaTI** [comment]
Currently, I used the font `JetBrainsMonoMedium Nerd Font 10pt`
I set up the font on konsole.
![image](https://user-images.githubusercontent.com/35637860/163730200-c209742e-798d-417c-b60f-3dc6fbc0d9ef.png)

**Comment by marko-cerovac** [comment]
This is really weird. Everything seems fine except for the italics. I'm gonna need some more info so that I can pinpoint where the issue is coming from. Have you tried other colorschemes with italics and do they work on other colorschemes? What terminal emulator are you using neovim in?

**Comment by ChavaTI** [comment]
Yeah tried color schemes differently and didn't work. I use Konsole and Alacrity in a Arch Linux

**Comment by marko-cerovac** [comment]
Then it has to be an issue with the terminal emulator or the font.
