### ISSUE TITLE
Error loading theme because the group Search is used before it is defined

### ISSUE THREAD

**Issue by folke** [marko-cerovac/material.nvim#9]
https://github.com/marko-cerovac/material.nvim/blob/064b5678eff31c68ea3b61836e3213d850c04b6c/lua/material.lua#L265

I'm getting the following error with the most recent ColorBuddy:
![image](https://user-images.githubusercontent.com/292349/115158450-014cde80-a043-11eb-9327-78238458210f.png)

Probably because the group Search is defined a couple of lines below the one I linked?

**Comment by marko-cerovac** [comment]
I've changed it and pushed it right now.
Can you let me know if the problem is still occurring because I don't think it's an issue with the Search group.

**Comment by folke** [comment]
Thanks! That one is fixed, but the same problem now with https://github.com/marko-cerovac/material.nvim/blob/6bcbeb8c2f9efa9281845b16a40cb96e7cb1d7fd/lua/material.lua#L627

**Comment by folke** [comment]
There's an issue about this at ColorBuddy: https://github.com/tjdevries/colorbuddy.nvim/issues/23

But changing the order fixes it. (Those other groups probably didnt work before)

**Comment by marko-cerovac** [comment]
I've gone over all highlight groups and removed all instances of bad definitions
Should be fixed now

**Comment by folke** [comment]
Great, works great now!
