### ISSUE TITLE
Material.nvim colored_cursor persists after exiting neovim

### ISSUE THREAD

**Issue by chris-av** [marko-cerovac/material.nvim#95]
Greetings,

Just noticed after updated my material.nvim via packer that my cursor changes color and that the color persists after exiting neovim. Would it be possible for material.nvim to detect whether the `vim.o.cursor` option is defined and, if so, to respect those configs? In the meantime I can set the `disable = { colored_cursor = true } }` to deactivate the cursor, but I imagine that the cursor persisting after exit is not the expected behavior of the plugin. 

Pretty sure the source of the bug is material but if you want to verify whether perhaps some of my other configs contribute, feel free to checkout my nvim config [here](https://github.com/chris-av/nvim).

```
Using MacOS Monterey
nvim v0.7.0
material.nvim commit 6133d4885891200d353ee20fb097cec80d1c3e9a, Sat May 7 04:33:39 2022 +0200
```

https://user-images.githubusercontent.com/41182258/167567414-e13704c2-1366-4b78-a4b3-6be41d975b09.mov

**Comment by marko-cerovac** [comment]
What terminal emulator are you using? I'm using alacritty and everything works fine. I've also made the theme remove the setting right before exiting neovim. Can you please let me know if the solution works. If it doesn't, than it's an issue with your terminal emulator and can't be fixed.

**Comment by chris-av** [comment]
>What terminal emulator are you using?

I am using iTerm2. Just tested with my computer's native Terminal app and it appears that the cursor did not persist like it did in the video. The behavior is reproducable with other terminal profiles within the iTerm2 app.

In case it matters, I am using iTerm2 Build 3.4.15, the latest version I think. Guess you are right though that it has more to do with the emulator. Sorry about that! Very weird!

Can probably close this issue for now but still interesting to note in case others encounter the same issues. I wonder if other terminal emulators (Hyper.js, etc.) also encounter this issue.
