### ISSUE TITLE
Palenight variant has no background

### ISSUE THREAD

**Issue by cynicade** [marko-cerovac/material.nvim#97]
First of all, thanks for the theme!
I'm facing an issue with the palenight variant having no background,
even with `disable = {
  background = false
}` set explicitly.

Here's a minimal config to reproduce the issue (at least on my system).
<details>
  <summary>Config</summary>
  
  ```lua
 -- ignore default config and plugins
vim.opt.runtimepath:remove(vim.fn.expand('~/.config/nvim'))
vim.opt.packpath:remove(vim.fn.expand('~/.local/share/nvim/site'))

-- append test directory
local test_dir = '/tmp/nvim-config'
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. '/pack/packer/start/packer.nvim'
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.cmd('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
  vim.cmd('packadd packer.nvim')
  install_plugins = true
end

local packer = require('packer')

packer.init({
  package_root = test_dir .. '/pack',
  compile_path = test_dir .. '/plugin/packer_compiled.lua'
})

packer.startup(function(use)
  -- Packer can manage itself
  use 'wbthomason/packer.nvim'
  use { 'marko-cerovac/material.nvim', config = function()
    require('material').setup({
      disable = {
        background = false
      }
    })
  end }

  if install_plugins then
    packer.sync()
  end
end)

vim.g.material_style = "palenight"
vim.cmd 'colorscheme material'

  ```
  
</details>

<details>
<summary>Screenshots</summary>

![palenight](https://user-images.githubusercontent.com/51382649/172442764-5784a721-0b72-4944-974a-1c2621c60ea4.png)

![lighter](https://user-images.githubusercontent.com/51382649/172442913-7a5ae24b-c3cb-42de-87e3-dd35ef9d2fb7.png)

![darker](https://user-images.githubusercontent.com/51382649/172442946-71799af0-dde7-4622-8a57-0374f20b1156.png)

</details>

EDIT: Just tested it on a VM and it works as intended, so this is an issue with my system.
Feel free to close or help me figure it out :)

**Comment by marko-cerovac** [comment]
Okay, this is weird. What version of Neovim, and what terminal emulator are you using. I also noticed that you are using a window manager, so this could potentially be an issue with the compositor.

**Comment by marko-cerovac** [comment]
Also does running this command give an error?
```:lua vim.opt.termguicolors=true```

**Comment by marko-cerovac** [comment]
Okay, that is really weird. I think that this is an issue with the compositor. Are you using picom/compton ?

**Comment by cynicade** [comment]
I can't know for sure if neovim gets a background if I remove transparency from kitty, since the issue is only present when kitty and neovim have the same background color. Therefore, if I disable transparency then I can't tell if the background comes from kitty or from neovim. Anyway, this is a super niche issue and as far as I can tell it doesn't stem from the theme/plugin so I'll close it. Thanks for your help and once again thanks for the theme :)

**Comment by marko-cerovac** [comment]
@cynicade I'm pretty sure that the issue stems from some kitty setting. If you need more help in solving this, feel free to write here.
